### ISSUE TITLE
Primal Tech Whittling Sticks Sometimes Work and Sometimes Don't

### ISSUE THREAD

**Issue by Vyraal1** [Vyraal1/FTB-Interactions#1]

**Comment by PsychoSound** [comment]
Boats seem to also not work sometimes. You can place them but you can't ride them. Relogging has fixed this issue so far.

**Comment by joral** [comment]
Not sure if this is related.  I have been trying to recreate the instances where this happens.  For me, it's always the first world I load after starting the client.  It does not matter if the world is pre-existing.  I don't know if these are in any way related, but I have always seen these errors logged the first time I log in on a client, and the fire stick/boat error happens for that login as well.  Any subsequent logins without restarting the client have neither these errors nor the fire stick problems.

[first_login_errors.log](https://github.com/Vyraal1/FTB-Interactions/files/2711110/first_login_errors.log)

**Comment by Saereth** [comment]
pretty sure this is the culprit
https://github.com/HellFirePvP/AstralSorcery/issues/952
