### ISSUE TITLE
F4, F5, F6, F7, F8, F9, F10, F11 and F12 all open the Nutrition GUI if the key is unbound

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vyraal1/FTB-Interactions#100]
By default, the Nutrition GUI is bound to N. It works as intended when it stays bound. If the key is unbound, all of the F keys except F1, F2 and F3 open the GUI.

**Comment by Saereth** [comment]
please report to the mod author
https://github.com/WesCook/Nutrition

**Comment by TheDeviantCrafter** [comment]
[Done](https://github.com/WesCook/Nutrition/issues/128)
