### ISSUE TITLE
[Bug] Starmetaldust unobtainable

### ISSUE THREAD

**Issue by TheonlyTazz** [Vyraal1/FTB-Interactions#101]
Can't convert the Iron Ore to Starmetal ore, breaking AS Progression? No Recipe leads to Startmetal dust nor Ore

![image](https://user-images.githubusercontent.com/3908847/50668210-f4189c80-0fbd-11e9-94b1-3ddff13c95a2.png)

**Comment by Saereth** [comment]
Not a bug
