### ISSUE TITLE
make quest for brine infrastructure in late LV era

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#104]
Probably start of mv, build a thermal evaporation tower, fuel wood heaters, explain relation to pyro/cryotheum etc

Submitter: Teamy#9201
Body: OwO issue "make quest for brine infrastructure in late LV era" "Probably start of mv, build a thermal evaporation tower, fuel wood heaters, explain relation to pyro/cryotheum etc"
Attachments:

**Comment by Saereth** [comment]
duplicate, REEE
https://github.com/Vyraal1/FTB-Interactions/issues/103
