### ISSUE TITLE
fix stats keeper so people stop respawning with full hunger

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#110]
Submitter: Saereth#7836
Body: OwO issue "fix stats keeper so people stop respawning with full hunger"
Attachments:

**Comment by Vyraal1** [comment]
god damn it i thought i fixed this

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/50702107-f9a5cf00-101d-11e9-94c5-70b500bfbd39.png)

**Comment by Vyraal1** [comment]
it should stay true right?

**Comment by Saereth** [comment]
it was in hungeroverhaul as well, got it
