### ISSUE TITLE
Quests for ContentTweaker infused ore blocks need to be updated/removed

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vyraal1/FTB-Interactions#112]
Version 54 removed the ContentTweaker infused ores. In the `A Little Less Safe` quest category, there are 6 quests that still require those ores. These need to be either removed or updated.

**Comment by TheonlyTazz** [comment]
Already Changed the Icons/Blocks, still need to add the Description(s). Only Aer was already filled in with description:

![image](https://user-images.githubusercontent.com/3908847/50728558-192b1d80-112c-11e9-9319-14bdf3f3356c.png)
