### ISSUE TITLE
[Suggestion] Keep /home, but give it a 4 hour cooldown

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vyraal1/FTB-Interactions#116]
Both /home and /island home will be disabled soon, which is a decision I agree with. Easy access to command based teleports makes teleporter items irrelevant.

However, there are some cases where I think a command like this would be required. If you get lost and can't find your portal, or if you somehow destroy it, you're screwed.

Keeping the command, but giving it an extremely long cooldown would let it work for cases like this without trivializing teleportation. It would only be practical as a break glass in case of emergency tool.

**Comment by TheDeviantCrafter** [comment]
I just broke my portal by mistake. I was on the overworld side with no philosopher's stone. I would have had to cheat or ask an admin for help to get back.

**Comment by Saereth** [comment]
home is not something we can control from a pack perspective, we cannot distribute the /local/ folder as it would overwrite ranks and permissions every time. Island has no such settings. 

in your scenario you could have just died.

**Comment by Saereth** [comment]
anyway gonna ship home on a 30min cooldown as pack default
