### ISSUE TITLE
[Suggestion] Move the basic GregTech tools to the artisan worktable

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vyraal1/FTB-Interactions#117]
When you check the recipe for the GregTech saw, you're greeted with 23 pages of recipes. Most of these have names like HSS-E and Red Garnet. It's quite intimidating to someone who has never used GregTech before.

Searching through that wall of recipes for one you can craft isn't exactly trivial. Since everything in GregTech is gated behind those tools, this information shouldn't be buried.

I recommend moving the basic tools of each type (saw, hammer, etc) to the artisan worktable. This would put the basic tools in a separate location, which the player is much more likely to find.

**Comment by Saereth** [comment]
I kinda feel like this is just delaying the inevitable, one way or another the player needs to understand the recipes shown in jei are representative of what they can make with most materials, thats the information I'd be more concerned with conveying to the player rather than an entirely alternate crafting system

**Comment by TheDeviantCrafter** [comment]
A delay is exactly what I think we need. Obviously the player will need to know this information eventually, but it's not needed to get started.

The more information you need to know up front, the more intimidating and difficult it is to get started.

Once th

**Comment by Saereth** [comment]
hrm alright we could probably do something like this, which tools specifically?

**Comment by TheDeviantCrafter** [comment]
Each of the tools you need for the low voltage tier. I think iron is the cheapest option, so move the iron variant of each basic LV tool to the artisan worktable.

Once the player reaches MV, or wants to upgrade to a better tool tier, that would be good time to expect them to know how to choose a metal.

I just want to make a fairly basic Gregtech setup with tools from the artisan worktable. Off the top of my head, I would add the iron variant of the hammer, saw, and file. I'm not at my computer so I may have missed a few.

**Comment by TheDeviantCrafter** [comment]
It looks like the hammer has been added to the artisan worktable. The file needs a similar treatment. I haven't gotten far enough into GregTech to know if any other tools should be added to the artisan worktable.

**Comment by Saereth** [comment]
I can do the hammer and file, all the rest require GT tools to create which the artisan table doesnt support, added next update
