### ISSUE TITLE
Crafting Logistic Pipe has no Recipe

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#120]
Cannot craft Request Table, Please provide alternative recipe if Pipe is disabled bcause of Auto-Crafting

Submitter: Interactions#0220
Body: **[TheonlyTazz]** OwO issue "Crafting Logistic Pipe has no Recipe" "Cannot craft Request Table, Please provide alternative recipe if Pipe is disabled bcause of Auto-Crafting"
Attachments:

**Comment by Saereth** [comment]
add emojiful
