### ISSUE TITLE
Can't Make TC6 Celestial Observations

### ISSUE THREAD

**Issue by random51** [Vyraal1/FTB-Interactions#134]
Resubmit from FTB gitlab for Saereth visibility.

Might be because the overworld isn't the dimension id TC6 expects, or it might be because of how Astral Sorcery changes the sky.

If it is AS, adding the overworld/void dimension ids to this part of the AS config might help:

```
# IF a dimensionId is listed in 'skySupportedDimensions' you can add it here to keep its sky render, but AS will try to render only constellations on top of its existing sky render. [default: ]
S:weakSkyRenders <
    145
    146
    147
    -2
 
```

**Comment by Saereth** [comment]
I suspect this is more related to the jed world handler  but I added it to see if it helps

**Comment by Saereth** [comment]
I changed this setting, let me know if it works

**Comment by ShaneCourtrille** [comment]
This is still not working
