### ISSUE TITLE
Can't Research Thaumium Essentia Smelter

### ISSUE THREAD

**Issue by random51** [Vyraal1/FTB-Interactions#135]
![smelter](https://user-images.githubusercontent.com/12644511/50732035-b63f8380-1137-11e9-80fa-1d4750e0a3fb.jpg)
Thaumonomicon is asking for Thaumium Plate(image is TC thaumium plate). GT Thaumium plate doesn't work. No apparent way to make a TC Thaumium plate.

This research is required to progress to Alchemical Automation which is presumably critical path for the wood/coal/coal coke/alumentum plan.

**Comment by Saereth** [comment]
fixed next update with a conversion shapeless
