### ISSUE TITLE
Vyraal to fix biome edge

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#139]
I thought I fixed this stupid biome edge

Submitter: `Vyraal1#0001`
Body: OwO issue fuuuuuuck I thought I fixed this stupid biome edge
Attachments:
![attachment](https://cdn.discordapp.com/attachments/527215210768105481/531336540115173376/unknown.png)

**Comment by xt9** [comment]
Vyraal has to work with Biomes again? F.
