### ISSUE TITLE
Low grade charcoal recipe only works with vanilla logs

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vyraal1/FTB-Interactions#140]
Vanilla logs can be placed in a clay kiln to get low grade charcoal. This doesn't work with modded logs, such as olive.

**Comment by Saereth** [comment]
unfortunately the kiln doesnt support oredict so we have to add every block manually, because of this we kinda focused around logs that are available in the void only, we can add oilve, let me know if there are any others you think we should add

**Comment by Saereth** [comment]
olive added for next update

**Comment by Gr8umbreon** [comment]
The rubber wood that you are asked to get in the "Safe Zone" questline, has the same problem. This also results in free xp.
