### ISSUE TITLE
remove the following from tinkers pickaxe casting

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#144]
knightslime, invar, obsidian, nickel

Submitter: `Saereth#7836`
Body: `OwO issue "remove the following from tinkers pickaxe casting" "knightslime, invar, obsidian, nickel"`
Attachments:

**Comment by Vyraal1** [comment]
really don't think these are that gamebreaking, and the reason I left them castable in the first place was because they're pretty niche/shit so only way theyll ever be used is if they can be casted. Regardless removed all of them and put them in Extruder.
