### ISSUE TITLE
CEU only accepts Basic Electronic Circuit

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#153]
Although it accepts any circuitBasic, it wont accept Basic Circuits

Submitter: `Tazz#0001`
Body: `OwO issue "CEU only accepts Basic Electronic Circuit" "Although it accepts any circuitBasic, it wont accept Basic Circuits"`
Attachments:

**Comment by Saereth** [comment]
asked him on his CF if he'd support naitvely as well
https://minecraft.curseforge.com/projects/ceu
