### ISSUE TITLE
Reneable arboreal extracto JEI category

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#157]
Submitter: `Interactions#0220`
Body: `**[Vyraal1]** OwO issue "Reneable arboreal extracto JEI category"`
Attachments:

**Comment by Vyraal1** [comment]
Oh thought this was resin funnel, there isn't a JEI category for the arboreal extractor, it's kind similar to the fishery where you just place it down and it works with no inputs.
