### ISSUE TITLE
Rustic Rope recipe doesn't oredict

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#158]
Twine can't be used to craft Ropes from Rustic

Submitter: `Interactions#0220`
Body: `**[Discomanco]** OwO issue "Rustic Rope recipe doesn't oredict" "Twine can't be used to craft Ropes from Rustic"`
Attachments:

**Comment by Discomanco** [comment]
Escape Rope from Random Things needs same treatment

**Comment by Discomanco** [comment]
Rope Ladder from Open Blocks as well

**Comment by Discomanco** [comment]
Ender Rope from Ender Utilities

**Comment by Vyraal1** [comment]
To a certain degree, i do want to nerf how stupid easy twine is and limit it's uses throughout. At some point players will need to make string, also thing about adding polyprolactam to the processing chain for some of these fiber based payoff tools.
