### ISSUE TITLE
Add kiln recipes for some foods

### ISSUE THREAD

**Issue by whizzball1** [Vyraal1/FTB-Interactions#16]
Rice bread is the only one I can think of.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/50520484-a3211980-0a8e-11e9-8a26-e8949142539f.png)

**Comment by Saereth** [comment]
closing, I made note of the rice bread on this thread:https://github.com/Vyraal1/FTB-Interactions/issues/8 

lets keep all food related stuff there for easy tracking
