### ISSUE TITLE
Fine Wire Recipes

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#161]
Need machine recipes for Fine Wire, is usually feeding wire back into wire mill

Submitter: `random51#7159`
Body: `OwO issue "Fine Wire Recipes" "Need machine recipes for Fine Wire, is usually feeding wire back into wire mill"`
Attachments:

**Comment by Vyraal1** [comment]
https://github.com/EmosewaPixel/GregicAdditions/issues/43

**Comment by Vyraal1** [comment]
temporarily fixed
