### ISSUE TITLE
Couple crashes while using JEI

### ISSUE THREAD

**Issue by Vexsanity** [Vyraal1/FTB-Interactions#17]
version .42
[crash-2018-12-27_00.40.11-client.txt](https://github.com/Vyraal1/FTB-Interactions/files/2714118/crash-2018-12-27_00.40.11-client.txt)
version .43
[crash-2018-12-28_00.48.19-client.txt](https://github.com/Vyraal1/FTB-Interactions/files/2714120/crash-2018-12-28_00.48.19-client.txt)

**Comment by Saereth** [comment]
thats some funky content tweaker block looks like, what were you searching for?
