### ISSUE TITLE
create LV age quest for the alternate way to make grains of infinity

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#181]
Submitter: `Saereth#7836`
Body: `OwO issue "create LV age quest for the alternate way to make grains of infinity"`
Attachments:

**Comment by Saereth** [comment]
lightwell + infinity powder = liquid nightmare, liquid nightmare in a solidifier with a nugget mold = infinity grains, grains in world spawn mobs that have a 35% chance to drop an infinity powder. with a dispenser and an auto killing setup they should be able to get all the grains they need + access to enderman/pearls before they've reached the nether to activate that gating.
