### ISSUE TITLE
Check CT support for adding coke to prim blast furnace

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#183]
shouldnt break anything

Submitter: `Interactions#0220`
Body: `**[Vyraal1]** OwO issue "Check CT support for adding coke to prim blast furnace" "shouldnt break anything"`
Attachments:

**Comment by Saereth** [comment]
This is currently no way to add new fuels to the primitive blast furnace

```
PBFRecipeBuilder.start()
    .input()
    .output()
    .duration()
    .fuelAmount()
    .buildAndRegister();
```
