### ISSUE TITLE
misspelling quest

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#193]
Submitter: `Deividas#2246`
Body: `OwO issue "misspelling quest"`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/526806854777438228/532687368730312704/unknown.png)

**Comment by TheonlyTazz** [comment]
no its correct...

The reward is, that WE tell YOU, that YOU can copy these with Plantballs

so with the us, it means us as packdev
