### ISSUE TITLE
GTCE block durability vs. appropriate tool

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#198]
TOP says right tool is pick but pick is much, much slower than wrench.

Submitter: `Interactions#0220`
Body: `**[random51]** OwO issue "GTCE block durability vs. appropriate tool" "TOP says right tool is pick but pick is much, much slower than wrench."`
Attachments:

**Comment by Saereth** [comment]
not sure what we can do about this or if its even an issue. Yes pick is a valid tool for it as in it wont break the block which is generally what TOP is indicating there, wrench is BETTER but both are valid.
