### ISSUE TITLE
[Bug] Animals cant use the Void-Overworld Portal

### ISSUE THREAD

**Issue by TheonlyTazz** [Vyraal1/FTB-Interactions#20]
Pic related:
![image](https://user-images.githubusercontent.com/3908847/50527203-240bff80-0ae7-11e9-8390-f5d21d60a32a.png)

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/50527287-b2808100-0ae7-11e9-88a6-63258815702b.png)
onward piggy!  but serious.. no piggybackpack doesnt work either (even tried with new created portal)

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/50532038-4bf86480-0ae1-11e9-8a2b-18b1ccac3100.png)
It's in his hands now.

**Comment by Saereth** [comment]
this isnt really a pack issue anymore since we added morbs to transport
