### ISSUE TITLE
[Bug] Drying racks can't be crafted

### ISSUE THREAD

**Issue by TheonlyTazz** [Vyraal1/FTB-Interactions#21]
Tinker's Construct "Drying Racks" can't be crafted, meaning you cant make the "Coagulated Blood Drop" which you need to make BloodMagic's Snares

![image](https://user-images.githubusercontent.com/3908847/50529478-5886b800-0af5-11e9-8f48-156afe7205c7.png)

**Comment by Vyraal1** [comment]
Should be crafted, and coagulated blood is craftable, we just had the blood drop category accidentally hidden, fixed.
