### ISSUE TITLE
Prismarine bricks only craftable in compressor

### ISSUE THREAD

**Issue by Doppelganker** [Vyraal1/FTB-Interactions#213]
Version: 0.56
Issue: Prismarine brick unlike other prismarine blocks which are craftable in crafting bench, is only made in gt compressor.

Edit: actually all vanilla 3x3 (same item) recipes are moved to compressor
Decorative block should be craftable

**Comment by Saereth** [comment]
most of these should all be in the compressor including the quarts block, giving an exception to prsimarine since the recipe sin the compressor would conflict so Im moving all prismarine to simple shapecraft to avoid conflicts and remain consistent within that material
