### ISSUE TITLE
aluminium dust quest explanation

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#219]
Sapphire, bentonite, green sapphire, emerald in centrifurge or thermal centrifuge route

Submitter: `Vyraal1#0001`
Body: `OwO issue "aluminium dust quest explanation" "Sapphire, bentonite, green sapphire, emerald in centrifurge or thermal centrifuge route"`
Attachments:

**Comment by codewarrior0** [comment]
I used an ore washer to get aluminium dust from sapphire ore and now the quest is sitting there incomplete, mocking me for being shrewd. Then, I started pouring the sapphire dust directly into the blast furnace so I wouldn't need any aluminium dust... that oughta show 'em!
