### ISSUE TITLE
[Suggestion] Remove "Lose hunger at all times"

### ISSUE THREAD

**Issue by Discomanco** [Vyraal1/FTB-Interactions#22]
For playstyles like mine, it's a huge miserable setting. I constantly switch between playing and going AFK for amounts of time, making me lose hunger twice as fast, while also doing nothing. Not super nice to come back from a 20min break and going from full hunger to near nothing while AFK

`hungeroverhaul\default.cfg`
```
    # You lose hunger (very slowly) at all times [vanilla: false] [default: true]
    B:constantHungerLoss=true
```

**Comment by Saereth** [comment]
its there to prevent people from just standing around as a chunkloader. Im fine with making it much less though we can set it to like 20% of the speed it is now. But there are items that can negate hunger issues entirely and this is just one more reason to make them.If you need to actually afk 2hrs might be worth just logging.

**Comment by Vyraal1** [comment]
I guess from a design perspective, should we even be trying to prevent that? I wouldn't really call it 2 hours, but more often than not I'd look up a Youtube spotlight of an unknown mod and would still get penalized for it. Also people hate Spice of Life enough already that alone is more than enough to convince people to go Nature's Leech or Vicio perks.

**Comment by Saereth** [comment]
yeah I dont agree, I'm not a fan of doing basically anything to make the pack easier and devalue items like that further. Its also not a huge sticking point either, change it if you want

**Comment by Discomanco** [comment]
Does a dead player still load chunks?
