### ISSUE TITLE
Pam's Press recipe for paper only accepts vanilla logs

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#236]
Can't use greatwood to make great paper. Sadness.

Submitter: `Interactions#0220`
Body: `**[Fako]** OwO issue "Pam's Press recipe for paper only accepts vanilla logs" "Can't use greatwood to make great paper. Sadness."`
Attachments:

**Comment by Saereth** [comment]
there is no ct support for pams, cant do anything about it
