### ISSUE TITLE
Silverwood leaves spawn in doomlike dungeons

### ISSUE THREAD

**Issue by MrNinja93** [Vyraal1/FTB-Interactions#238]
Not sure if you guys were wanting to gate silverwood access entirely behind astral sorcery but just in-case the leaves are able to generate within doomlike dungeons so sapling drop is a possibility.

**Comment by Saereth** [comment]
nah its fine, you can get them via exploration as well if you just find a magical forest biome, we're ok with the trade off of exploration vs hard progression basement dwelling
