### ISSUE TITLE
steel ingot tooltip has primitive misspelled https://i.imgur.com/s0NacN8.png

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#250]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "steel ingot tooltip has primitive misspelled https://i.imgur.com/s0NacN8.png"`
Attachments:

**Comment by Vyraal1** [comment]
can't reproduce, even with base tier iron armor they only do 7 hearts, you aren't mean to fighting freezers with leather.
