### ISSUE TITLE
Bellows also multiplies the output amount

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#253]
Attaching Bellows to the Infernal Furnace also multiplies the output, or some of it. 3 Bellows on the Infernal Furnace, threw in 1 stack of Crude Steel, got 1 stack of Slag and 4 stacks of Steel back. Doesn't seem intended, otherwise very strong

Submitter: `Discomanco#2559`
Body: `OwO issue "Bellows also multiplies the output amount" "Attaching Bellows to the Infernal Furnace also multiplies the output, or some of it. 3 Bellows on the Infernal Furnace, threw in 1 stack of Crude Steel, got 1 stack of Slag and 4 stacks of Steel back. Doesn't seem intended, otherwise very strong"`
Attachments:

**Comment by Saereth** [comment]
hrm I suppose we could have the base recipe give 3 nuggets of steel so with full bellows you get 12 nuggets or something?

**Comment by TheonlyTazz** [comment]
12nuggets of steel for 1 iron ingot... Seems a good trade-off

Saereth <notifications@github.com> schrieb am Mo., 14. Jan. 2019, 15:57:
