### ISSUE TITLE
Lower Tier Cables cant be automated with assembler

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#261]
only with a packer, needs carpet, whereas all other cables can be covered with rubber

Submitter: `Interactions#0220`
Body: `**[TheonlyTazz]** OwO issue "Lower Tier Cables cant be automated with assembler" "only with a packer, needs carpet, whereas all other cables can be covered with rubber"`
Attachments:

**Comment by Vyraal1** [comment]
This is general GT progression as there really isn't a fluid equivalent for wool to make it fit in an assembler. The other issue is that implementing these wire recipes might be a bit much for a (relatively )small portion of the game that you use tin cables, still considering it.
