### ISSUE TITLE
Rough Mobs Crash

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#262]
https://minecraft.curseforge.com/projects/rough-mobs-2/issues/36

Submitter: `Vyraal1#0001`
Body: `OwO issue "Rough Mobs Crash" "https://minecraft.curseforge.com/projects/rough-mobs-2/issues/36"`
Attachments:

**Comment by TheonlyTazz** [comment]
Looking through the Crashlog, it seems to be an issue bteween Rough-Mobs and Emberroots (Ancient Golem to be precise)
maybe as a temporary fix, we could disable spawning the Ancient Golem in the Emberroots.cfg
`entityancientgolem {
    # Sometimes attacks hostile mobs. [default: true]
    B:AttacksMobs=true

    # Try to spawn in every biome.  If false, it will use the whitelist in this config  [default: true]
    B:allBiomes=true 

    # Base attack, before weapons and buffs [range: 0.0 ~ 100.0, default: 5.0]
    S:baseDamage=5.0

    # Biomes this will spawn into.  Add support for any modded biome here.  Ignored whenever allBiomes is true. https://minecraft.gamepedia.com/Data_values#Biome_IDs [default: ]
    S:biomeWhitelist <
     >`

by changing B:allBiomes to False and leave the Whitelist empty

 `# Try to spawn in every biome.  If false, it will use the whitelist in this config  [default: true]
    B:allBiomes=false`

**Comment by Vyraal1** [comment]
Whoops shoulve closed tihs earlier, i fixed the crash by removing the golems ability to attack hostile mods. I already contacted lothrazar and epic squid about it
