### ISSUE TITLE
Fluid Solidifier Glass only takes

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#263]
Submitter: `Interactions#0220`
Body: `**[TheonlyTazz]** OwO issue "Fluid Solidifier Glass only takes`
Attachments:

**Comment by TheonlyTazz** [comment]
144Mb, not 1000mb as 1block of glass = 1000mb giving you more glass for your sand

**Comment by TheonlyTazz** [comment]
Minecraft.zs:
```
	#glass
fluidExtractor.recipeBuilder()
    .inputs(<ore:sand> * 1)
    .fluidOutputs([<liquid:glass> * 144]) #needs to be 1000
    .duration(80)
    .EUt(28)
    .buildAndRegister();
```

**Comment by Vyraal1** [comment]
Scripts are organized by the output of the item, considering that you have various mod crafting chains progressing one after another, it gets messy really quickly
