### ISSUE TITLE
Drying rack doesn't have a recipe

### ISSUE THREAD

**Issue by Jomeaga** [Vyraal1/FTB-Interactions#27]

**Comment by Vyraal1** [comment]
NBT tags strike again, should be visible in the next update. 
![image](https://user-images.githubusercontent.com/26587049/50542427-e2cd2b80-0b8a-11e9-993e-17b9ec556e40.png)

![image](https://user-images.githubusercontent.com/26587049/50542428-e82a7600-0b8a-11e9-8760-ea4bd5dd8b73.png)
Is the recipe at the moment, but the biggest issue has constantly been NBT tags screwing up recipes in JEI.
