### ISSUE TITLE
Shift clicking a recipe into the basic worktable voided the ingredients and the tool.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#271]
Submitter: `Interactions#0220`
Body: `**[coolprez]** OwO issue "Shift clicking a recipe into the basic worktable voided the ingredients and the tool."`
Attachments:

**Comment by Vyraal1** [comment]
https://github.com/codetaylor/artisan-worktables/issues/149

**Comment by Saereth** [comment]
awaiting this pr acceptance and new build deployment
https://github.com/mezz/JustEnoughItems/pull/1466
