### ISSUE TITLE
Oak fence gates have no essentia, while other wooden gates do.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#272]
Either oak fence gates need 5 vinculum and 5 machina, or other gates need values cleared.

Submitter: `Interactions#0220`
Body: `**[Kezzar_Gassi]** OwO issue "Oak fence gates have no essentia, while other wooden gates do." "Either oak fence gates need 5 vinculum and 5 machina, or other gates need values cleared."`
Attachments:

**Comment by Saereth** [comment]
if people want to submit zenscript for adding essential to items we'll accept and include it, otherwise there are more than enough items to burn for essentia already and far tooo many items without essentia for us to bother adding to it all.
