### ISSUE TITLE
Aqua-infused Ore and Terra-infused Ore giving more than one ore

### ISSUE THREAD

**Issue by PsychoSound** [Vyraal1/FTB-Interactions#28]
Earlier today this happened but I logged on later and it seemed to have fixed itself. The Aqua ore dropped 21 ore when I broke it and the Terra ore dropped 2 ore.

Edit: In the same instance as the ores working correctly, it started dropping extras again...

**Comment by Saereth** [comment]
wtf...

**Comment by Saereth** [comment]
I've tried several times and not been able to reproduce this yet, can anyone else confirm/help reproduce?

**Comment by Saereth** [comment]
migrating this ticket to https://github.com/Vyraal1/FTB-Interactions/issues/55
