### ISSUE TITLE
Plant balling double tall flowers is inconsistent.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#280]
Plant ball on top creates a flower one block tall you can shear for more petals, but balling the bottom instead creates a flower you can't collect.

Submitter: `Interactions#0220`
Body: `**[Fako]** OwO issue "Plant balling double tall flowers is inconsistent." "Plant ball on top creates a flower one block tall you can shear for more petals, but balling the bottom instead creates a flower you can't collect."`
Attachments:

**Comment by Saereth** [comment]
we'll blacklist them

**Comment by Vyraal1** [comment]
```
plantball {
    # A list of blacklisted registry names, or modids.  Strings without a ":" will be treated as modids. [default: ]
    S:"Plantball Blacklist" <
        botania:flower
        botania:shinyflower
        botania:doubleflower1
        botania:doubleflower2
     >
}```
