### ISSUE TITLE
Water Powered Saw removes NBT

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#281]
Submitter: `Interactions#0220`
Body: `**[Escapee_]** OwO issue "Water Powered Saw removes NBT"`
Attachments:

**Comment by Saereth** [comment]
yes and there isnt anything we can do about that since the saw doesnt support nbt, what problem is this causing so we can just remove the offending planks?

**Comment by TheonlyTazz** [comment]
Hé sawed his satchel, removing the content in it... Tbh. If u pull your
satchel through a saw, it's normal you wouldn't get your stuff back xD

Saereth <notifications@github.com> schrieb am Fr., 18. Jan. 2019, 14:33:

**Comment by TheonlyTazz** [comment]
IS this an artisans worktable block? If so, maybe report there and link to
this issue

murapix <notifications@github.com> schrieb am Sa., 19. Jan. 2019, 08:29:

**Comment by Saereth** [comment]
https://github.com/vadis365/PrimalTech/issues/29

**Comment by Saereth** [comment]
this has been reported everywhere it can be closing since its not a pack specific issue
