### ISSUE TITLE
Gem refiner & Forge hammer allow for resource loop

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#288]
Exquisite gems (made in refiner) can be hammered for two gems. Recommend reduce forge hammer output to 1.

Submitter: `Interactions#0220`
Body: `**[Fako]** OwO issue "Gem refiner & Forge hammer allow for resource loop" "Exquisite gems (made in refiner) can be hammered for two gems. Recommend reduce forge hammer output to 1."`
Attachments:

**Comment by Vyraal1** [comment]
its flawless gems, and flawless gems require two gems
