### ISSUE TITLE
rubber trees do not work with tree beacons

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#289]
Probably gtce bypassing normal on growth events (or whatever its called), basically the tree beacon does not 'ghost' the blocks and allow drops normally

Submitter: `IRSmoh_#5048`
Body: `OwO issue "rubber trees do not work with tree beacons" "Probably gtce bypassing normal on growth events (or whatever its called), basically the tree beacon does not 'ghost' the blocks and allow drops normally"`
Attachments:

**Comment by Vyraal1** [comment]
https://github.com/GregTechCE/GregTech/issues/509
already fixed
