### ISSUE TITLE
client crash with piston moving industrial foregoing conveyor

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#295]
Specifically it was tested with a sticky piston and pulling, but it causes a tessellation crash and duplicates the belt (well, it spawned an additional black one)

Submitter: `IRSmoh_#5048`
Body: `OwO issue "client crash with piston moving industrial foregoing conveyor" "Specifically it was tested with a sticky piston and pulling, but it causes a tessellation crash and duplicates the belt (well, it spawned an additional black one)"`
Attachments:

**Comment by Saereth** [comment]
I really need a crashlog to take to Buuz

**Comment by Saereth** [comment]
https://github.com/Buuz135/Industrial-Foregoing/issues/496

**Comment by Saereth** [comment]
Moving Tile entities is always gonna be dicey when they arent mean to, this is not vanilla functionality and its quark doing things that TEs werent really meant to do, just dont do it :P might disable that quark feature if this continues to be an issue but I suspect it wont be a major issue
