### ISSUE TITLE
vision helmet removes pitch darkness

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#297]
equip a vision helmet from cyclic, take it off, wait for the 20s buff to end, it gets stuck at 0:00 but the buff effectivelyish goes away, however normal minecraft light levels persist instead of total darkness. https://i.imgur.com/0DG95Zq.png

Submitter: `IRSmoh_#5048`
Body: `OwO issue "vision helmet removes pitch darkness" "equip a vision helmet from cyclic, take it off, wait for the 20s buff to end, it gets stuck at 0:00 but the buff effectivelyish goes away, however normal minecraft light levels persist instead of total darkness. https://i.imgur.com/0DG95Zq.png"`
Attachments:

**Comment by Saereth** [comment]
This screenshot doesnt show the buff durations getting stuck, please add a SS of that so I can refer this to the cyclic dev

**Comment by IRSmoh** [comment]
https://i.imgur.com/koBhFHv.png

**Comment by Saereth** [comment]
https://github.com/Lothrazar/Cyclic/issues/975

**Comment by Saereth** [comment]
mod interaction, minimal impact, closing since it'll likely not get fixed
