### ISSUE TITLE
Thermal Hammer destroying machines.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#298]
First encounter resulted in the destruction of some machine I can't remember. A cable dropped instead of the machine. Could not reproduce. Second encounter, accidentally hammered a x1 copper wire, an LV -> MV transformer, an MV extruder, an LV Input Hatch, and the main hatch of the electric blast furnace. Contents of the machines dropped while the machines themselves did not. Testing by IRSmoh_ demonstrated that the TE diamond hammer, as well as something most likely mining things the same way (Flux Infused Hammer from redstone arsenal), would consistently destroy machines, only returning parts instead of the whole.

Submitter: `DearDeathDay#1116`
Body: `OwO issue "Thermal Hammer destroying machines." "First encounter resulted in the destruction of some machine I can't remember. A cable dropped instead of the machine. Could not reproduce. Second encounter, accidentally hammered a x1 copper wire, an LV -> MV transformer, an MV extruder, an LV Input Hatch, and the main hatch of the electric blast furnace. Contents of the machines dropped while the machines themselves did not. Testing by IRSmoh_ demonstrated that the TE diamond hammer, as well as something most likely mining things the same way (Flux Infused Hammer from redstone arsenal), would consistently destroy machines, only returning parts instead of the whole."`
Attachments:

**Comment by DearDeathDay** [comment]
-Machine destroyed, dropped contents. Could not reproduce. 
-5 machines and 1 wire destroyed. 
-Mining multi-blocks w/TE Hammer or Flux Infused Hammer resulted in total destruction and minimal return on materials. Reproducible.

**Comment by Vyraal1** [comment]
items refunded, investigating and recording in single player

**Comment by KingLemming** [comment]
Unsure what is "correct" behavior here - GT's intention is that only wrenches are supposed to work at all. The fact that pickaxes work at all is actually a bug on their end.

So technically, CoFH is 8x more correct than everything else. :P

**Comment by Saereth** [comment]
This is intended behavior (mostly) from the gTCE dev, machines should be Wrenched, TE is not at fault here
https://imgur.com/a/Bz8AgPG
