### ISSUE TITLE
clarify that mystic flowers are only from Jaded Amaranthus

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#300]
otherwise they need to make mystical petals from various plants

Submitter: `Vyraal1#0001`
Body: `OwO issue "clarify that mystic flowers are only from Amaranthus" "otherwise they need to make mystical petals from various plants"`
Attachments:

**Comment by Saereth** [comment]
Jaded amaranthus :P

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/53307023-3e1e5000-3894-11e9-86fb-16108ef455a4.png)
