### ISSUE TITLE
More expensive bandage is worse option than band aid

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#304]
Both provide .5 hearts of healing when used, but bandage has 13 uses (to bandaid 21), and takes twice as long to use

Submitter: `Interactions#0220`
Body: `**[Fako]** OwO issue "More expensive bandage is worse option than band aid" "Both provide .5 hearts of healing when used, but bandage has 13 uses (to bandaid 21), and takes twice as long to use"`
Attachments:

**Comment by Saereth** [comment]
TODO: remove/hide that bandage from jei but still let it be a loot item, use the bandaid item in stead in the higher tier medkits as a subcomponent
