### ISSUE TITLE
Advanced Motor doesnt have a texture

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#312]
Advanced Rocketry pls... it seems an item bug, but dont know how to resolve

Submitter: `Tazz#0001`
Body: `OwO issue "Advanced Motor doesnt have a texture" "Advanced Rocketry pls... it seems an item bug, but dont know how to resolve"`
Attachments:

**Comment by TheonlyTazz** [comment]
By placing it down and breaking it again, the item gets us texture back

**Comment by Saereth** [comment]
reported to mod dev ages ago
