### ISSUE TITLE
Certus Quartz -> Flawed Certus not working

### ISSUE THREAD

**Issue by Jomeaga** [Vyraal1/FTB-Interactions#32]
![2018-12-29_22 54 08](https://user-images.githubusercontent.com/31868004/50544221-baf6bb80-0bbc-11e9-872c-d4d18f98879d.png)
![2018-12-29_23 06 16](https://user-images.githubusercontent.com/31868004/50544288-648a7c80-0bbe-11e9-9747-cb9942a89236.png)

**Comment by TheonlyTazz** [comment]
Because probably the intended way is doing it via the forge hammer, which does work... Check the 3rd tab of the recipe... 

All in all, I think the crafting recipe should be disabled

**Comment by Saereth** [comment]
yeah those recipes should be done in the forge hammer, I'll see about removing the shapecraft recipes
