### ISSUE TITLE
Feedback from the Void World play-through

### ISSUE THREAD

**Issue by cScotPlay** [Vyraal1/FTB-Interactions#33]
///Void World Feedback///

Please take this feedback for what it’s worth; the ramblings of an old guy that loves the game of MC.  I absolutely love the concept of this pack or at least the void world.  It is awesome to see the pack start off in a void world and not use Ex Nihilo or Sky Resources.  I just finished the Void World and am happy to finally find the Overworld.  It took me approximately 14 hours to get from the start to the Overworld.  Please take in mind that I am really slow and I had to research a fair amount of things as I hadn’t dealt with some of the mods before i.e. Primal Tech, Tinkers Complement, From the Depths.  

Earlier this year, we built a skyblock pack that revolved around Primal Core and did not include the previously mentioned skyblock mods.  The comments and questions that we received about our pack are what drive the feedback that I want to provide you all.  What we learned was people were really hesitant to play a pack that didn’t have mods they were familiar with.  We tried to negate this issue by having a quest book that taught the player these mods.  We were somewhat successful but it still brought a lot of questions and criticism (maybe I just suck at writing quest).  I feel that Interactions is in this category and again that is where my feedback will be focused.  Sorry for the rambling but I wanted to validate where I am coming from with the feedback.

With that out of the way let here is what I ran across:
	
- Again, I love the concept of the Void World.  It gives a nice early game feel and slowly brings the player into the pack.  I personally found the quest line to be helpful but not in your face about what to do exactly and allowed me to explore both the mods and the gameplay.  I’ve also learned that a lot of players will want the quest line to lead them in a step by step manner get to the Overworld.  I wish I knew the proper ratio of freedom versus hand holding.  If it wouldn’t have been for the Discord channel I would have been held up on a couple of quest due to not knowing exactly how to progress.  (Filo Stone, fomdog melter, Leather Tunic)
  - Filo Stone – I was able to spawn the Zombie Villager and feed him the Apple of Restoration but it took me a couple of times to actually figure out the mechanics of it.  A little more explanation may help a bit.
  - fomdog melter - May be worth adding one of the lava containers as another item to craft as it is required to make the system work.  Not using this mod I had to research a bit on how it went together.
  - Leather Tunic – Getting the Candleberry seed was a guessing game and thanks to the Discord channel for the help.  JEI didn’t initially show that it was with the Arcane Ash.  It now shows but it something to think about with other quests.

- I really like how a lot of the early game mods all relate and build on each other.  Tinkers Compliment created from clay found in the Water Strainers and can produce Terracotta. Artesian Worktables helping to craft things.  Primal Tech creating food and resources and so on.  I really enjoyed this thanks for thinking through each of these interactions.
	
- Quest rewards.  Thank you for not spamming us with loot chest of other items that may not be needed until later game.  The food in the Void World quest was really nice.  I personally hate getting all the crap from quest and considering that early game storage is very limited to vanilla chest, I thank you for not adding more items to our inventories.  I found out that a fair amount of people don’t like this and want to be showered with useless items.  I guess it comes from a school of thought that I want to earn what I get and it makes it more rewarding when I finally get the items.
- Quark or Cyclic add an option to craft four chest with eight logs.  It currently shows up in JEI but is not craftable.  Please remove this recipe if you want the player to make the Wood Casing to craft the chest.
- I know that we are playing on the old quest for the Overworld Portal but it may be worth adding some verbiage that tell the player they need to use the Philosopher’s Stone to ignite the portal.

Overall I really enjoyed the challenge of the early game and Void World.  It made me think about future steps and plan out how I wanted to accomplish certain tasks.  The grind didn’t feel overly forced and I flowed from one quest/challenge to the next pretty easily.  Again, I am not a fast player or a super knowledgeable with some of the mods (just ask Guy he will validate my incompetents) but I enjoy the game and the challenge of finding my own personal way through mudpack.  It feels like you have left a bit of self-learning and discovery in there that rewards the player for thinking through things.  Thanks again for listening to the ramblings of this old guy that has a serious love of the game and I am excited to get to the Overworld and try my hand at some GregTech.

**Comment by Saereth** [comment]
I think we've resolved all these issues now, great post and thanks for the feedback
