### ISSUE TITLE
FTB Quests dumping you out of JEI

### ISSUE THREAD

**Issue by Zetharion** [Vyraal1/FTB-Interactions#331]
Right click on any item like an oak sapling that is used in a quest.  You have all the tabs across the top including one for FTB Quests.  Click on that one.  Now click on the smaller left or right arrows on either side of where it says Quests.  It dumps you out of JEI and into the FTB Quests selection area.

Any players that are just clicking along will get dumped out once they get to the FTB Quests Tab.

**Comment by Saereth** [comment]
I cant reproduce this, can you share some screenshots or a video?

**Comment by Zetharion** [comment]
One example is to search for oak sapling in JEI and right click on it.  Then click on the FTB Quests tab along the top of the JEI Box.

![dump to ftb quests issue screengrab 1](https://user-images.githubusercontent.com/8367380/51865422-d2d07500-230b-11e9-9293-74363afbc980.jpg)

Then click on either of the arrows on the left or right, I highlighted the right one in the image.  When you do it dumps me into the FTB Quests screen.

![dump to ftb quests issue screengrab 2](https://user-images.githubusercontent.com/8367380/51865490-06130400-230c-11e9-888a-e5a898478568.jpg)
