### ISSUE TITLE
please

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#334]
disable Owls from Emberroot if possible, huge lag issue when on snow

Submitter: `Tazz#0001`
Body: `OwO issue please disable Owls from Emberroot if possible, huge lag issue when on snow`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/527215210768105481/539392030472929281/unknown.png)

**Comment by TheonlyTazz** [comment]
removed Owls from spawning in every biome, enabled in forest and dark forest
