### ISSUE TITLE
Add tooltip to Mekanism's Thermal Evaporation Controller.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#335]
Players that have used them in the past assume they need solar, which is no longer true.  Suggest putting 'Solar Panels cannot be obtained; external heat must be provided to the structure' as a tooltip to try to minimize confusion and erroneous bug reports.

Submitter: `Fako#0163`
Body: `OwO issue "Add tooltip to Mekanism's Thermal Evaporation Controller." "Players that have used them in the past assume they need solar, which is no longer true.  Suggest putting 'Solar Panels cannot be obtained; external heat must be provided to the structure' as a tooltip to try to minimize confusion and erroneous bug reports."`
Attachments:

**Comment by TheonlyTazz** [comment]
Added Tooltip
"Solar Panels cannot be obtained; external heat must be provided to the structure"
