### ISSUE TITLE
Myrmex Queen Egg crash without nearby players

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#345]
If you get a Myrmex Queen Egg, then don't happen to be more than 15 blocks away the moment it hatches, the game will crash, losing you the egg in the process

Submitter: `Escapee#6378`
Body: `OwO issue "Myrmex Queen Egg crash without nearby players" "If you get a Myrmex Queen Egg, then don't happen to be more than 15 blocks away the moment it hatches, the game will crash, losing you the egg in the process"`
Attachments:

**Comment by Saereth** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/1354

**Comment by Alex-the-666** [comment]
hi, we have just resolved this issue in ice and fire.

the fix will be in release 1.7.0.
