### ISSUE TITLE
Mana Concentrator issues in v.61

### ISSUE THREAD

**Issue by FakoTheGreat** [Vyraal1/FTB-Interactions#353]
The modular machine for making unstable mana is... unstable right now.  The following issues have been observed on the testing server:

- If there are multiple power catalysts in the input hatch, all will be consumed simultaneously on rare occasion.
- When making unstable mana, sometimes water is produced.
- During the refining process, multiple power catalysts can be required and subsequently consumed, as it repeatedly procs the 5% chance to consume.

**Comment by DearDeathDay** [comment]
I think when the machine runs out of mana it auto-consumes all the available catalysts, running the machine rn with mana input from 4 pertorpetunias running at once and it seems to be working fine, made 2+ b w/1 catalyst which fits the consumption chance

**Comment by Saereth** [comment]
https://github.com/DaedalusGame/Modular-Diversity/issues/30

**Comment by Saereth** [comment]
also reported to hellfire
https://github.com/HellFirePvP/ModularMachinery/issues/147
