### ISSUE TITLE
No vanilla slime ball recipes for TC hedge alchemy pre-steam

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#358]
Earliest method I can find now that the press is removed is to either get lucky and find a slime or get into steam and make a macerator for the plant ball to make a slime sapling.

Submitter: `Interactions#0220`
Body: `**[Fako]** OwO issue "No vanilla slime ball recipes for TC hedge alchemy pre-steam" "Earliest method I can find now that the press is removed is to either get lucky and find a slime or get into steam and make a macerator for the plant ball to make a slime sapling."`
Attachments:

**Comment by Saereth** [comment]
you can get it from water traps, jelly fish convert 1 to 1 into slimeballs
