### ISSUE TITLE
Stacks of cells ignore hot or not effects

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#359]
https://i.imgur.com/MicFiw4.png https://i.imgur.com/97OXTA0.png probably not really fixable but may as well report it

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Stacks of cells ignore hot or not effects" "https://i.imgur.com/MicFiw4.png https://i.imgur.com/97OXTA0.png probably not really fixable but may as well report it"`
Attachments:

**Comment by Saereth** [comment]
yeah cells are a type of container so not really a bug
