### ISSUE TITLE
all cables all burned at the same time according to IRSMoh and Fako regardless of amperage or voltage

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#361]
Submitter: `Vyraal1#0001`
Body: `OwO issue "all cables all burned at the same time according to IRSMoh and Fako regardless of amperage or voltage"`
Attachments:

**Comment by TheonlyTazz** [comment]
Did you guys use the time in the bottle?

**Comment by Saereth** [comment]
I cannot reproduce this...

**Comment by Vyraal1** [comment]
same, cant reproduce, gona close and wait for a reproduction
