### ISSUE TITLE
[RECIPE_ERROR] Firestick have two recipes

### ISSUE THREAD

**Issue by Doppelganker** [Vyraal1/FTB-Interactions#37]
Version: 0.47

Issue: There are to very similar recipes. One is probably not intended.
![image](https://user-images.githubusercontent.com/17344502/50550169-ff409500-0c6a-11e9-98f8-07006bd97efd.png)

**Comment by Vyraal1** [comment]
Latter is intended, the first recipe can cause crashes in rares circumstances. Removing the first recipe.
