### ISSUE TITLE
[REVIEW] Finished Void Stage - impresions

### ISSUE THREAD

**Issue by Doppelganker** [Vyraal1/FTB-Interactions#38]
This was my second time completing void stage, first time it took me 6 h, this time I finished 3, but without finishing full leather armour yet.

Void stage as a start is really good feeling as a player, you don't need to rush anything, because your save from mobs. Giving player early EMC and building blocks in tablet, so you can easily extend your platform. (why nerf torches :( ) The saw change are feeling much better, so planks are not an annoyance anymore. All the progression feels natural, biggest complaint is waiting for zombie villager (but zensummoning was made to help with that).
There are still some inconsistencies (like wood barks only used for wood bucket, maybe add kiln recipe bark -> piece of charcoal, no way to fully automate kiln ...), but overall it plays goood.

Complexity so far is not to hard for seasoned player, much easier start than GTNH or similar packs. Interactions (praise me Vyraal) are really intriguing and looking farther in JEI, pack looks like a lot of fun. I'm really excited to delve into early magic mods, and scared of f*** mobs, why must I be so shit at combat.

P.S.: O, and when you finish progression, prepare for my post spamming about cleaning oredict.

**Comment by Saereth** [comment]
thanks for the feedback, added a new early game torch recipe using the barkwood, I'm closing this but i've marked with the purple label so we can refer back to it. Any oredicting issues you see we definitely want to resolve so thanks for that!
