### ISSUE TITLE
ironwood

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#383]
needs saw-recipe

Submitter: `Interactions#0220`
Body: `**[TheonlyTazz]** OwO issue ironwood needs saw-recipe`
Attachments:

**Comment by TheonlyTazz** [comment]
Correction, it has a normal crafting recipe for ironwood logs to planks
![image](https://user-images.githubusercontent.com/3908847/52380474-38400680-2a6e-11e9-8d4c-b2e17320e488.png)
