### ISSUE TITLE
Bauxite taking almost 100minutes to electrolyze?

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#390]
Submitter: `Tazz#0001`
Body: `OwO issue "Bauxite taking almost 100minutes to electrolyze?"`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/527215210768105481/543003021878231050/unknown.png)

**Comment by Saereth** [comment]
https://github.com/GregTechCE/GregTech/issues/554
