### ISSUE TITLE
Elementum armour

### ISSUE THREAD

**Issue by Doppelganker** [Vyraal1/FTB-Interactions#394]
version: 0.62
Issue: There is a mix in upgrading to elementum armour chestplate takes helmet, boots take leggings and viceversa

**Comment by Saereth** [comment]
what?

**Comment by Doppelganker** [comment]
Sorry, was reporting late at night, i don't know what the hell was that writing. So the issue is that elementum chestplate uses lethear helmet in the recipe, instead of chestplate, and other 3 recipes are equally wrong.

**Comment by Saereth** [comment]
oh ok np
