### ISSUE TITLE
Explain that Monkeyflower is a desert flower... so you need to plantball sand

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#395]
Submitter: `Vyraal1#0001`
Body: `OwO issue "Explain that Monkeyflower is a desert flower... so you need to plantball sand"`
Attachments:

**Comment by Saereth** [comment]
tooltip I guess?

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/52535142-1afb8880-2d4b-11e9-838f-97597cf45027.png)
it sais so as itemname: Plants2:desert_0 should be obvious

**Comment by Saereth** [comment]
I added a tooltip
