### ISSUE TITLE
Fluid Extractor unforgiving on power input.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#396]
Not sure if intended, but since the update all recipes in the fluid extractor require exact ratings of each power tier (32, 128 or 512) to function without issue.

Submitter: `Interactions#0220`
Body: `**[Fako]** OwO issue "Fluid Extractor unforgiving on power input." "Not sure if intended, but since the update all recipes in the fluid extractor require exact ratings of each power tier (32, 128 or 512) to function without issue."`
Attachments:

**Comment by Saereth** [comment]
https://github.com/GregTechCE/GregTech/issues/556
