### ISSUE TITLE
Enemies from the 'Laser Creeper Robot Dino Riders From Space' mod spawned in the OW, had been to both space and the moon, by accident, at the time.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#397]
Submitter: `DearDeathDay#1116`
Body: `OwO issue "Enemies from the 'Laser Creeper Robot Dino Riders From Space' mod spawned in the OW, had been to both space and the moon, by accident, at the time."`
Attachments:

**Comment by Saereth** [comment]
yep not a bug, once you unlock them they can invade you
