### ISSUE TITLE
Fire wires recipes got removed

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#409]
got commented out on the gregtech.zs

Submitter: `Tazz#0001`
Body: `OwO issue "Fire wires recipes got removed"  "got commented out on the gregtech.zs"`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/527215210768105481/544149416404189206/unknown.png)

**Comment by Saereth** [comment]
I see the scripts were commented out, whats up here @Vyraal1
