### ISSUE TITLE
Pyrolyse quest in MV, but tell players that most of it will be useful later on in EV

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#419]
Submitter: `Vyraal1#0001`
Body: `OwO issue "Pyrolyse quest in MV, but tell players that most of it will be useful later on in EV"`
Attachments:

**Comment by Saereth** [comment]
Particularly, it CAN be useful in MV for getting all the byproducts for polyethylene and biodiesel as well as the stuff for rocket fuel (ammonia) but it will become an integral part of their infrastructure once they can make distillation towers.
