### ISSUE TITLE
Osmium can be obtained in the overworld stage, albeit painfully.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#425]
Process requires crushing and washing chalcopyrite, then using a chem reactor (LV Recipe) with nitric acid (made from air and water) to get a tiny pile of platinum sludge dust. Combine into proper pile, then centrifuge for the following: Guaranteed Silicon Dioxide, guaranteed tiny gold dust, guaranteed tiny platinum dust, 60% chance for tiny osmium, 60% chance for tiny iridium, and 80% chance for tiny palladium. This doesn't allow you to use it early, but it can definitely be obtained early if the player's persistent (minimum 40.5 chalcopyrite ore per osmium dust, if all goes well) which allows for early Mek speed upgrades and the like.

Submitter: `Fako#0163`
Body: `OwO issue "Osmium can be obtained in the overworld stage, albeit painfully." "Process requires crushing and washing chalcopyrite, then using a chem reactor (LV Recipe) with nitric acid (made from air and water) to get a tiny pile of platinum sludge dust. Combine into proper pile, then centrifuge for the following: Guaranteed Silicon Dioxide, guaranteed tiny gold dust, guaranteed tiny platinum dust, 60% chance for tiny osmium, 60% chance for tiny iridium, and 80% chance for tiny palladium. This doesn't allow you to use it early, but it can definitely be obtained early if the player's persistent (minimum 40.5 chalcopyrite ore per osmium dust, if all goes well) which allows for early Mek speed upgrades and the like."`
Attachments:

**Comment by Saereth** [comment]
we discussed this before as I found it ages ago, I'm against this recipe remaining but I dont think we definitively agreed to remove it or not, any word on your stance for this @Vyraal1 ?
