### ISSUE TITLE
Create a questline for tungstenate processing

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#451]
Submitter: `Interactions#0220`
Body: `**[Saereth]** OwO issue "Create a questline for tungstenate processing"`
Attachments:

**Comment by Saereth** [comment]
should mention endstone from moon turf + starlight transmutation  or DML, then the endstone gets macerated and centrifuged or run through the infernal deconglomerator (better option) to obtain tungstenate, then ultimate EV Electrolyzed for tungsten dust
