### ISSUE TITLE
Alcara constellation paper crafting crashes server

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#458]
https://gist.github.com/Vyraal1/4ba5c5892f59fa4d2cf5612fb80c4d87

Submitter: `Vyraal1#0001`
Body: `OwO issue "Alcara constellation paper crafting crashes server" "https://gist.github.com/Vyraal1/4ba5c5892f59fa4d2cf5612fb80c4d87"`
Attachments:

**Comment by Vyraal1** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/1010
