### ISSUE TITLE
Liquid Starlight is actually not Too Cold To Handle in either a regular or clay bucket

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#460]
Submitter: `Interactions#0220`
Body: `**[Zetharion]** OwO issue "Liquid Starlight is actually not Too Cold To Handle in either a regular or clay bucket"`
Attachments:

**Comment by Saereth** [comment]
https://github.com/Buuz135/HotOrNot/issues/10

**Comment by Saereth** [comment]
its in gods hands now

**Comment by Zetharion** [comment]
Sorry meant to close this on my own.  I did get the effects the next time I carried a bucket around.
