### ISSUE TITLE
Review if AR Precision Assembler is actually needed

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#469]
We removed AR Chemical Reactor, should we just remove this multiblock? I cant remember the reason why Sae wanted it

Submitter: `Vyraal1#0001`
Body: `OwO issue "Review if AR Precision Assembler is actually needed" "We removed AR Chemical Reactor, should we just remove this multiblock? I cant remember the reason why Sae wanted it"`
Attachments:

**Comment by Saereth** [comment]
it has more varied input supports than gt machines the only thing comperable would be an assembler which doesnt look nearly as cool

**Comment by Vyraal1** [comment]
ok aesthetics works for me, im cool with it
