### ISSUE TITLE
Review ender pearl from non-wireless based automation recipes, eg Thermal Logistics or servos

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#470]
Submitter: `Vyraal1#0001`
Body: `OwO issue "Review ender pearl from non-wireless based automation recipes, eg Thermal Logistics or servos"`
Attachments:

**Comment by Saereth** [comment]
whats the issue here?

**Comment by Saereth** [comment]
will review any specific items you have concerns with, closing for now
