### ISSUE TITLE
Since today (20th Feb), can't autocraft machines that need a wrench

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#480]
Wrenches are always 'missing', even with ore-dict substitutions

Submitter: `Tazz#0001`
Body: `OwO issue "Since today (20th Feb), can't autocraft machines that need a wrench" "Wrenches are always 'missing', even with ore-dict substitutions"`
Attachments:
![image](https://user-images.githubusercontent.com/3908847/53088040-e8028300-3508-11e9-8170-03194d96ebe3.png)

![image](https://user-images.githubusercontent.com/3908847/53088021-dfaa4800-3508-11e9-8c1b-abb76b2293b4.png)

**Comment by TheonlyTazz** [comment]
NVM im just dumb and it was just a case of broken wrench 🤦‍♂️
