### ISSUE TITLE
Soulus recipe passthrough been

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#486]
putting it off due to metallurgy, can do it one day, gona put it at T3 Altar and Attunement in astral

Submitter: `Vyraal1#0001`
Body: `OwO issue "Soulus recipe passthrough "been putting it off due to metallurgy, can do it one day, gona put it at T3 Altar and Attunement in astral"`
Attachments:

**Comment by Vyraal1** [comment]
done
