### ISSUE TITLE
Resonate ender is only craftable through the melter

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#488]
That seems like a massive, massive tech down grade for the usual requirements..... aka we're making chaotic injectors (basically ev)

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Resonate ender is only craftable through the melter" "That seems like a massive, massive tech down grade for the usual requirements..... aka we're making chaotic injectors (basically ev)"`
Attachments:

**Comment by IRSmoh** [comment]
>resonant
I can't spell

**Comment by Saereth** [comment]
a fluid extractor recipe has already been added for next update
duplicate post
https://github.com/Vyraal1/FTB-Interactions/issues/453
