### ISSUE TITLE
chorus fruit can be obtained from thauncraft rare bags (loot)

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#494]
making end dimension available pre-euclydes

Submitter: `Tazz#0001`
Body: `OwO issue "chorus fruit can be obtained from thauncraft rare bags (loot)" "making end dimension available pre-euclydes`
Attachments:

**Comment by IRSmoh** [comment]
I mean you still have to craft the evil tear.

**Comment by Saereth** [comment]
tc does not expose these loot tables, will have to change the end rod recipe or something
