### ISSUE TITLE
Fine Soldering wire uncraftable blame Arch

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#499]
Aka hudlense currently cannot be crafted.

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Fine Soldering wire uncraftable blame Arch" "Aka hudlense currently cannot be crafted."`
Attachments:

**Comment by TheonlyTazz** [comment]
Duplicate of https://github.com/Vyraal1/FTB-Interactions/issues/491
