### ISSUE TITLE
Coal Coke lost its texture

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#500]
probably due to ID-Issue

Submitter: `Tazz#0001`
Body: `OwO issue "Coal Coke lost its texture" "probably due to ID-Issue"`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/527215210768105481/548835158586032129/unknown.png)

**Comment by Vyraal1** [comment]
known, probably will have to refund anyone else but shouldn't be that big of a deal since most people had renewable/infinite setups, coal coke switched ID's
