### ISSUE TITLE
Fine wire can no longer be made in any machines, only using the wire cutter. This has serious problems for circuit construction.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#503]
Submitter: `Kel#1990`
Body: `OwO issue "Fine wire can no longer be made in any machines, only using the wire cutter. This has serious problems for circuit construction."`
Attachments:

**Comment by Saereth** [comment]
duplicate
https://github.com/Vyraal1/FTB-Interactions/issues/491
