### ISSUE TITLE
Ender tank uncraftable due to no stainless barrel...

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#504]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "Ender tank uncraftable due to no stainless barrel..."`
Attachments:

**Comment by Vyraal1** [comment]
using stainless steel pipe instead 
![image](https://user-images.githubusercontent.com/26587049/53492986-344d4600-3a68-11e9-964d-201719f02b0f.png)
