### ISSUE TITLE
Thaumcraft Thaumium Plate uncraftable? All recipe give GTCE version which the Thaumonomicon doesnt recognize for completion of Essentia Smelter

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#507]
Submitter: `Interactions#0220`
Body: `**[Zetharion]** OwO issue "Thaumcraft Thaumium Plate uncraftable? All recipe give GTCE version which the Thaumonomicon doesnt recognize for completion of Essentia Smelter`
Attachments:

**Comment by Zetharion** [comment]
Its the Thaumium Essentia Smelter research under the Alchemy tab.

**Comment by Vyraal1** [comment]
fixed
