### ISSUE TITLE
Add a Flint Saw to the Worktable Quest

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#509]
Explain people to use the Worktable to cut planks in the Worktable instead of right clicking logs for planks

Submitter: `Tazz#0001`
Body: `OwO issue "Add a Flint Saw to the Worktable Quest" "Explain people to use the Worktable to cut planks in the Worktable instead of right clicking logs for planks"`
Attachments:

**Comment by Vyraal1** [comment]
Added
![image](https://user-images.githubusercontent.com/26587049/53340564-5499cb00-38d7-11e9-99b6-3b631fe00045.png)
Although this is pretty obvious in JEI by going through the tabs, not sure if this counts as too much handholding.
