### ISSUE TITLE
brick forms are getting used up in recipes, making polymer caly stupidly expensive

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#514]
Submitter: `Vyraal1#0001`
Body: `OwO issue "brick forms are getting used up in recipes, making polymer caly stupidly expensive"`
Attachments:

**Comment by Vyraal1** [comment]
seems like this is fixed in latest GTCE, however patcher is no longer being updated, going to need to find an alternate solution

**Comment by Vyraal1** [comment]
Removing the recipe and replacing it doesn't seem to work, looks like there's some funky transformers in the wooden form that always transforms it into a glass bottle even with the script below.

```
	#Compressed Clay (brick form gets consumed)
recipes.remove(compressedClay);
recipes.addShaped(compressedClay * 8,[
	[<minecraft:clay_ball>, <minecraft:clay_ball>, <minecraft:clay_ball>],
	[<minecraft:clay_ball>, <metaitem:wooden_form.brick>.reuse(), <minecraft:clay_ball>],
	[<minecraft:clay_ball>, <minecraft:clay_ball>, <minecraft:clay_ball>]]);
```

Going to add a substitute recipe that uses chemical reactor + liquid polyethylene that uses more power.
