### ISSUE TITLE
Photonuclear reactor doesn't run 100% even with sufficient inputs

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#517]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "Photonuclear reactor doesn't run 100% even with sufficient inputs"`
Attachments:

**Comment by IRSmoh** [comment]
https://youtu.be/fXDb1BUQDHA is a video demo

**Comment by Vyraal1** [comment]
Can't reproduce https://streamable.com/s4gwp

**Comment by Vyraal1** [comment]
will log into server later to investigate

**Comment by Vyraal1** [comment]
Looks like it was an output hatch, it might check for a large enough buffer instead of every single tick, seems to work perfectly fine with an output hatch that's twice as large. Might look into reducing amount of total MM output hatches types to 3  and simplying their recipes.
