### ISSUE TITLE
remove useless slime boot recipe

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#52]
![image](https://i.imgur.com/6jwxJ9Z.png)

Submitter:Teamy#9201
Body: OwO issue "remove useless slime boot recipe" "[image](https://i.imgur.com/6jwxJ9Z.png)"

**Comment by Saereth** [comment]
this isnt useless, slimeboots are obtainable as loot and you can then apply this upgrade
