### ISSUE TITLE
WHO added this quest again!?

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#520]
Recipe not working anyway tho <:kappa:432194889623666690> ... still shows up in JEI

Submitter: `Tazz#0001`
Body: `OwO issue "WHO added this quest again!?" "Recipe not working anyway tho <:kappa:432194889623666690> ... still shows up in JEI"`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/527215210768105481/550108145511432193/unknown.png)

**Comment by Vyraal1** [comment]
Which quest were you referring to again?

**Comment by TheonlyTazz** [comment]
not quest... recipe ... derp
