### ISSUE TITLE
Quartz slivers cant be crafted pre-lv since the quartz ores cant be smelted anymore.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#521]
Submitter: `coolprez#8206`
Body: `OwO issue "Quartz slivers cant be crafted pre-lv since the quartz ores cant be smelted anymore."`
Attachments:

**Comment by Vyraal1** [comment]
fixed, added squeezer route that directly outputs one nether quartz per ore
