### ISSUE TITLE
Blaze, Blitz, Basalz, Blizz dont drop mobdrops when killed with ritual of culling

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#523]
Submitter: `Interactions#0220`
Body: `**[TheonlyTazz]** OwO issue "Blaze, Blitz, Basalz, Blizz dont drop mobdrops when killed with ritual of culling"`
Attachments:

**Comment by Vyraal1** [comment]
Not really sure if this is a problem that needs to be fixed, as we want to encourage DML anyways. But it is inconsistent with other mobs.

**Comment by Saereth** [comment]
this is not a bug, it doesnt kill as a player so it doesnt give you player only drops, you can use a discidia ritual for this if you absolutely want to go that route, otherwise DML is your  path for farming those drops and outside the scope of culling ritual
