### ISSUE TITLE
For some reason 1 ore and 1 dirt creates 4 of the corresponding dust

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#524]
Submitter: `Kel#1990`
Body: `OwO issue "For some reason 1 ore and 1 dirt creates 4 of the corresponding dust"`
Attachments:

**Comment by TeamDman** [comment]
https://cdn.discordapp.com/attachments/527215210768105481/550400729215533057/2019-02-27_14.35.44.png

Apparently the recipe doesn't work?
![image](https://user-images.githubusercontent.com/9356891/53518033-1dc1e180-3a9e-11e9-992e-2b55b549a212.png)

**Comment by Vyraal1** [comment]
It was a test zenClass script, I commented it out, it shouldnt be there anymore. But even weirder that the recipe doesn't work, ill let kindlich know
