### ISSUE TITLE
Re-add betterbuildingwands

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#526]
Without it building actual useful size platforms is exceedingly tedious, and building a large floating field is suicidal

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Readd exu2 builder wands" "Without it building actual useful size platforms is exceedingly tedious, and building a large floating field is suicidal"`
Attachments:

**Comment by IRSmoh** [comment]
betterbuildingwands*** not exu2

**Comment by Vyraal1** [comment]
could've been convinced, but the hyperbole made me decide otherwise
