### ISSUE TITLE
try to find a way to 100% prevent rain in aurellia, horrible lag occurs otherwise

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#528]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "try to find a way to 100% prevent rain in aurellia, horrible lag occurs otherwise"`
Attachments:

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/53540655-6a301000-3ae4-11e9-8e3f-18320f3bf420.png)

**Comment by IRSmoh** [comment]
>oh hey I don't even have to post to ignore it because theres going to be no sane way of repoing it due to being a client specific lag that occurs even on relaunch

**Comment by IRSmoh** [comment]
wew that looks broken
![image](https://user-images.githubusercontent.com/2626462/53543364-11fb0d00-3ae8-11e9-9638-24930fb6d1a4.png)
