### ISSUE TITLE
double check barium/niobium recipes

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#544]
check in GTNH and gregblock how it was created

Submitter: `Vyraal1#0001`
Body: `OwO issue "double check barium/niobium recipes" "check in GTNH and gregblock how it was created"`
Attachments:

**Comment by Vyraal1** [comment]
Add Barite oregen to the End and in Nether

**Comment by Vyraal1** [comment]
Niobium from purified piles of tantalite
![image](https://user-images.githubusercontent.com/26587049/53676224-421fe880-3c6d-11e9-9071-740d2ffc1d6d.png)

**Comment by Vyraal1** [comment]
Make sure there is sufficient tantalite or a multiplier for tantalite.
