### ISSUE TITLE
make an assembler recipe for pumps

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#546]
super conductors require lv pumps, and you need a shit load of super conductors

Submitter: `IRSmoh_#5048`
Body: `OwO issue "make an assembler recipe for pumps" "super conductors require lv pumps, and you need a shit load of super conductors"`
Attachments:

**Comment by Saereth** [comment]
https://github.com/Vyraal1/FTB-Interactions/issues/550
duplicate
