### ISSUE TITLE
GA removal planning

### ISSUE THREAD

**Issue by Saereth** [Vyraal1/FTB-Interactions#549]
Items to port from Gregic additions:
Wafers
- [ ] 	 Wafer
- [ ] 	 SOC
- [ ] 	 RAM
- [ ] 	 Qbit
- [ ] 	 PIC
- [ ] 	 NOR
- [ ] 	 Naquadah doped
- [ ] 	 Glowstone doped
- [ ] 	 NanoCPu
- [ ] 	 Nand Memory chip
- [ ] 	 HPIC Wafer
- [ ] 	 CPU
- [ ] 	 Integrated logic circuit
- [ ] 	 Asoc Wafer

	
Circuits

- [ ] 	 Good
- [ ] 	 Advanced
- [ ] 	 Nano
- [ ] 	 quantum processor
- [ ] 	 crystal processor
- [ ] 	 wetware processor

	
boules

- [ ] 	 Monocrystaline silicon boules
- [ ] 	 naquadah doped Monocrystaline silicon boules
- [ ] 	 glowstone doped Monocrystaline silicon boules

- [ ] mixed metal plate
- [ ] advanced alloy
- [ ] raw carbon fibers
- [ ] assembly line casing
- [ ] reinforced glass
- [ ] Neutron reflector
- [ ] uncompressed iridium alloy
- [ ] iridium alloy plate
- [ ] stem cells

SMD components

- [ ] 	 transistor
- [ ] 	 SMD transistor
- [ ] 	 SMD resistor
- [ ] 	 SMD Capacitor
- [ ] 	 SMD Diode
- [ ] 	 resistor
- [ ] 	 capacitor
- [ ] 	 diode
- [ ] 	 vacuum tube
- [ ] 	 basic circuit
- [ ] 	

circuit boards

- [ ] 	 plastic good circuit board
- [ ] 	 phenolic circuit board
- [ ] 	 multilayer fiber reinforced circuit board
- [ ] 	 fiberreinforced circuit board
- [ ] 	 epoxy circuit board
- [ ] 	 coated circuit board

- [ ] petri dish
- [ ] glass tube
- [ ] glass fiber

High tier /nonexistant machines
- [ ] 	 IV/LuV Universal Assembler (this will not inheriet base assembler recipes from base GT but be used 

exclusively for high tier recipes)

- [ ] 	 Mass fabricator
- [ ] 	 Replicator
- [ ] 	 Naquadah reactor EV/IV/LuV
- [ ] 	 Fusion reactor
- [ ] 	 assembly line

**Comment by Vyraal1** [comment]
https://docs.google.com/spreadsheets/d/1Vy1BsLAag6-FtsMhm9C6PLhwDElvU9m8XZRMoZRuaSQ/edit#gid=28417530

**Comment by Saereth** [comment]
no longer relevant I guess
