### ISSUE TITLE
Dupe involving ContentTweaker ore 

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#55]
Broken with a Pickle Tweaks flint pickaxe WITHOUT holding the veinminer keybind https://streamable.com/5yisr

Submitter:Teamy#9201
Body: OwO issue "Dupe involving ContentTweaker ore + pure daisy" Broken with a Pickle Tweaks flint pickaxe WITHOUT holding the veinminer keybind https://streamable.com/5yisr
Attachments:

**Comment by TeamDman** [comment]
sitrep: works without pure daisy

**Comment by Saereth** [comment]
duplicate https://github.com/Vyraal1/FTB-Interactions/issues/28

**Comment by Vyraal1** [comment]
Can't seem to replicate. Did the server restart between when the video was taken and right now? Also vein miner keybind shouldn't matter, these ores should be blacklisted.

**Comment by Saereth** [comment]
I havent been able to duplicate this since the last update either

**Comment by Saereth** [comment]
we moved to GT ores so no longer an issue for our pack
