### ISSUE TITLE
Consider rebalacing ZPM

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#552]
At the point you can make the multiblock... you could just instead make a fusion reactor making it wholy redundant

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Consider rebalacing ZPM" "At the point you can make the multiblock... you could just instead make a fusion reactor making it wholy redundant"`
Attachments:

**Comment by Saereth** [comment]
this doesnt make it redundant, naquadah reactors are single block, portable high yield power sources. Yes you can make fusion but naquadah can actually be used to get you to fusion and great for one offs
