### ISSUE TITLE
Crystallized oil from canola has no heavy fuel conversion in distillery

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#554]
oil from canola has no heavy fuel conversion in distillery

Submitter: `108r5meme#8686`
Body: `>OwO issue Crystallized oil from canola has no heavy fuel conversion in distillery`
Attachments:

**Comment by Vyraal1** [comment]
should be an easy fix, just switching the `.notconsumable` to be using `.property("circuit", X)` where X is the configuration
