### ISSUE TITLE
cyberware stuff still doesn't drop on death

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#555]
Submitter: `Interactions#0220`
Body: `**[IRSmoh_]** OwO issue "cyberware stuff still doesn't drop on death"`
Attachments:

**Comment by Saereth** [comment]
it's been set since weds we just havent updated yet, told you it's fixed for next update
```
gamerules {
    S:"Chance of successful drop"=100.0
    B:"Default for gamerule cyberware_dropCyberware"=true
    B:"Default for gamerule cyberware_keepCyberware"=false
}
```
