### ISSUE TITLE
Fine Iridium wire has no crafting recipe

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#556]
No recipe to craft Fine Iridium Wire in a wire mill, only craftable via wirecutters and iridium plate

Submitter: `Wired_4fun#0248`
Body: `OwO issue "Fine Iridium wire has no crafting recipe" "No recipe to craft Fine Iridium Wire in a wire mill, only craftable via wirecutters and iridium plate"`
Attachments:

**Comment by Vyraal1** [comment]
might bbe better to instead make it require naquadah / naquadah alloy fine wire instead of iridium since iridium is a dense alloy used for plating. Also iridum doesnt have a cable in base GTCe and would have to generate one.
