### ISSUE TITLE
terrasteel rotor blades can be macerated for 6 dust while only taking 3.5 to make

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#561]
the way of reacquiring the ingots is through the tcon meltery

Submitter: `IRSmoh_#5048`
Body: `OwO issue "terrasteel rotor blades can be macerated for 6 dust while only taking 3.5 to make" "the way of reacquiring the ingots is through the tcon meltery"`
Attachments:

**Comment by Saereth** [comment]
other materials should be reviewed for this same issue

**Comment by Saereth** [comment]
This appears to be a gtce core issue, referring to GTCE issue tracker, if there is no resolution pre pack launch we will have to write some scripts to address this. 

https://github.com/GregTechCE/GregTech/issues/607
