### ISSUE TITLE
Quartzes arent smeltable making slivers and vis resonators not craftable before lv

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#562]
Submitter: `coolprez#8206`
Body: `OwO issue "Quartzes arent smeltable making slivers and vis resonators not craftable before lv"`
Attachments:

**Comment by Vyraal1** [comment]
this should be fixed already, duplicate of https://github.com/Vyraal1/FTB-Interactions/issues/521

**Comment by Vyraal1** [comment]
Actually another issue came up with this, you need to autoclave chipped quartz to get the slivers, was there another way to get slivers? @Saereth

**Comment by Saereth** [comment]
there is an alternate route already in place you shape craft flawed quartzite/quartz/certus into 2 chipped and then you starlight altar transform them to slivers, its the way to make them pre-autoclave and there is a quest for it already in the magic stick questline
