### ISSUE TITLE
move ender chest/tanks to thaumcraft infusuion, also master list of TC suggestions here

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#565]
Items to move to infusion crafting:
add dragon armors from ice and fire to TC infusion

- [x] Ender chest
- [x] Ender Tank

Dragon armors:

- [x] Red
- [x] Emerald
- [x] Bronze
- [x] Gray
- [x] Blue
- [x] White
- [x] Sapphire
- [x] Silver

- [x] HV tier item collector

- [x] ender bucket
- [x] apotheosis books
- [x] repair talisman

- [x] creative thaum - crimson rites + thaumcraft + primordial pearl + 1-2 of each knowledge frag + human brain

**Comment by Saereth** [comment]
add dragon armors from ice and fire to TC infusion

**Comment by Saereth** [comment]
add HV infusion recipe for item collectors

**Comment by Saereth** [comment]
ender bucket
apotheosis books
repair talisman

**Comment by Saereth** [comment]
creative thaum - crimson rites + thaumcraft + primordial pearl + 1-2 of each knowledge frag + human brain
