### ISSUE TITLE
Coal, Silicon, Diamond, Emerald, Lapis, Gold, Iron, Uranium, Nether Quartz, Redstone Chickens don't lay enriched eggs, instead laying the actual ingot/gem.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#571]
Submitter: `coolprez#8206`
Body: `OwO issue "Coal, Silicon, Diamond, Emerald, Lapis, Gold, Iron, Uranium, Nether Quartz, Redstone Chickens don't lay enriched eggs, instead laying the actual ingot/gem."`
Attachments:

**Comment by Vyraal1** [comment]
fixed
