### ISSUE TITLE
Chickens Issue(s)

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#574]
Glowstone chicken doesnt drop anything, Tungsten/Zinc drop actual ingot

Submitter: `Tazz#0001`
Body: `OwO issue "Chickens Issue(s)" "Glowstone chicken doesnt drop anything, Tungsten/Zinc drop actual ingot"`
Attachments:

**Comment by Vyraal1** [comment]
fixed the drops, disabled glowstone chicken, decided that glowstone multiplication isn't worth it. can revise
