### ISSUE TITLE
cannot craft ender heads https://i.imgur.com/fwbH88W.png hearts take priority

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#587]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "cannot craft ender heads https://i.imgur.com/fwbH88W.png hearts take priority"`
Attachments:

**Comment by Saereth** [comment]
this may be a bug in MM then, can you ensure you had the liquid xp in the machine? 

1bucket unstable mana, 40mb liquid xp

```
mmBuilder.newBuilder("enderHead", "alchemical_matter_infuser", 1000)
	.addItemInput(<deepmoblearning:pristine_matter_enderman>)
	.addFluidInput(<liquid:unstable_mana> * 1000)
	.addFluidInput(<liquid:xpjuice> * 40)
	.addItemOutput(<enderio:block_enderman_skull> * 16)
	.build();
```

**Comment by Saereth** [comment]
I cannot reproduce this 
![image](https://user-images.githubusercontent.com/9200909/54279251-fde4f000-456a-11e9-933e-d90ec52f533a.png)
