### ISSUE TITLE
review nitre production line

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#588]
Submitter: `Saereth#7836`
Body: `OwO issue "review nitre production line"`
Attachments:

**Comment by Vyraal1** [comment]
Thinking about making two ways:
1. Nether Ore generation + ore multiplication (probably up to 6x along with the other dusts ores)
2. Blitz Farm as a renewable source from pristine matter

**Comment by Saereth** [comment]
biotite is already a renewable source of potassium which you can convert into niter, just need to add a quest explaining it I guess. You can also get potassium from mineralis ritual (rock salt) directly which is even much faster we just need to get this information to the players

**Comment by Vyraal1** [comment]
What's all this for again? Niter for making blitz powder or something?

**Comment by Saereth** [comment]
yeah for pyrotheum/cryotheum which is now heavily used in ore multipliication

**Comment by Saereth** [comment]
added salt peter directly attainable via mineralis ritual
