### ISSUE TITLE
European (needed for mk2 reactor) cannot be made in mk1

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#589]
It takes 1.5 million eu to start the craft, but mk1 is limited to 800k

Submitter: `IRSmoh_#5048`
Body: `OwO issue "European (needed for mk2 reactor) cannot be made in mk1" "It takes 1.5 million eu to start the craft, but mk1 is limited to 800k"`
Attachments:

**Comment by Vyraal1** [comment]
user error
