### ISSUE TITLE
Bending machines (ev and below) require a wrench to craft

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#593]
Ideally they wouldn't but if its desired assembler recipe(?), specific machines are: Basic Bending Machine, Advanced Bending Machine [ ,II, III]

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Bending machines (ev and below) require a wrench to craft" "Ideally they wouldn't but if its desired assembler recipe(?), specific machines are: Basic Bending Machine, Advanced Bending Machine [ ,II, III]"`
Attachments:

**Comment by Saereth** [comment]
after reconsidering this there isnt enough need to automate these to really warrant these being autoamted in assemblers
