### ISSUE TITLE
beg quat for botania mana pylon enchantment config

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#595]
https://github.com/quat1024/BotaniaTweaks/issues/47

Submitter: `Saereth#7836`
Body: `OwO issue "beg quat for botania mana pylon enchantment config" "https://github.com/quat1024/BotaniaTweaks/issues/47"`
Attachments:

**Comment by Saereth** [comment]
new apotheosis config should solve this for now, if it gets added to botania tweaks later we'll use that too

**Comment by quat1024** [comment]
hello, i added this to botania tweaks 1.8.5 which is approving on curse
