### ISSUE TITLE
Custom infusion recipes taking primordial pearls expect full

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#603]
so now you have a ton of left over primordial pearls with tiny durability damage on them..

Submitter: `Interactions#0220`
Body: `**[IRSmoh_]** OwO issue "Custom infusion recipes taking primordial pearls expect full" "so now you have a ton of left over primordial pearls with tiny durability damage on them.."`
Attachments:

**Comment by Saereth** [comment]
added repair interaction with sky cauldron
