### ISSUE TITLE
Gregtech bronze pipes wont input steam into basic steam turbine. Bug or some new mechanic?

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#606]
Submitter: `Interactions#0220`
Body: `**[Zetharion]** OwO issue "Gregtech bronze pipes wont input steam into basic steam turbine. Bug or some new mechanic?"`
Attachments:

**Comment by Saereth** [comment]
This is a known issue, fixed in gtce update, just use other pipes as a work around for now
