### ISSUE TITLE
Check server crashlogs, supposedly it crashed due to zen summoning -coolprez

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#608]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "Check server crashlogs, supposedly it crashed due to zen summoning -coolprez"`
Attachments:

**Comment by Saereth** [comment]
ez fix im sure teamy will have us sorted soon

**Comment by TeamDman** [comment]
https://github.com/TeamDman/ZenSummoning/commit/cbd9a2d54f86429c856dc6b1e87ebb5c1c4f4110
Fixed
