### ISSUE TITLE
Crucible recipes not showing up in JEI.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#612]
Submitter: `coolprez#8206`
Body: `OwO issue "Crucible recipes not showing up in JEI."`
Attachments:

**Comment by coolprez** [comment]
Amendment: It's not just crucible recipes, no thaumcraft recipes show up in JEI. As well, you can still craft items in the crucible, so presumably all the thaumcraft recipes work, but are not showing up in JEI.
