### ISSUE TITLE
Thaumcraft JEI section showing which items have which aspects not showing up.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#617]
Submitter: `coolprez#8206`
Body: `OwO issue "Thaumcraft JEI section showing which items have which aspects not showing up."`
Attachments:

**Comment by Saereth** [comment]
we disabled thaumic jei aspects from item stacks for general buginess. It was making Thaumcraft recipes not show in jei and the aspects were often completely wrong even with a fresh item scan
