### ISSUE TITLE
Cauldron crafting with a hammer made from a hammer head is not working. Check scripts maybe? The hammer seems to work still with normal GT recipes.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#618]
Submitter: `Kel#1990`
Body: `OwO issue "Cauldron crafting with a hammer made from a hammer head is not working. Check scripts maybe? The hammer seems to work still with normal GT recipes."`
Attachments:

**Comment by Saereth** [comment]
once we update gtce this is  resolved
