### ISSUE TITLE
finish revamp of asteroid and gas mining missions

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#622]
Submitter: `Saereth#7836`
Body: `OwO issue "finish revamp of asteroid and gas mining missions"`
Attachments:

**Comment by Saereth** [comment]
asteroids are revamped still need to do the gas planets

**Comment by Saereth** [comment]
not gonna do gas giant mining missions they're just not worth the investment when all gases already have a way of bring produced by gt inherently
