### ISSUE TITLE
Sooty marble recipe with charcoal isnt showing up in JEI

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#625]
Submitter: `coolprez#8206`
Body: `OwO issue "Sooty marble recipe with charcoal isnt showing up in JEI"`
Attachments:

**Comment by coolprez** [comment]
Amendment: the recipe with charcoal doesn't work either

**Comment by coolprez** [comment]
Amendment: Tested it in both a steam and lv alloy smelter, worked in neither.
