### ISSUE TITLE
Power IC has not cutting machine recipe

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#635]
Submitter: `Wired_4fun#0248`
Body: `OwO issue "Power IC has not cutting machine recipe"`
Attachments:

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/54391689-f5c8a580-467b-11e9-9c9f-3523e504db9a.png)
More specifically it seems like there is a Power IC Wafer duplicates itself, the Wafer could bbe cutting into Power IC

**Comment by Vyraal1** [comment]
https://github.com/GregTechCE/GregTech/issues/639
