### ISSUE TITLE
Shift clicking results out of a crafting table causes disconnects.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#636]
Submitter: `coolprez#8206`
Body: `OwO issue "Shift clicking results out of a crafting table causes disconnects."`
Attachments:

**Comment by coolprez** [comment]
Amendment: Disconnects caused after not only shift clicking, but also repeatedly clicking the results out of a crafting table.

**Comment by Saereth** [comment]
@coolprez can you please post your latest.log here directly after you get this to happen

**Comment by Saereth** [comment]
I cannot reproduce this thus far, tried stacks of crafting tables 
, here is a log from coolprez for reference
https://cdn.discordapp.com/attachments/527215210768105481/555498172844343326/latest.log

**Comment by Saereth** [comment]
this seems to be limited to tinkers tables so far

**Comment by codewarrior0** [comment]
Not fixed in v72. Attached debugger and found Soulus recipe responsible:

https://github.com/Yuudaari/soulus/pull/72

**Comment by TeamDman** [comment]
How did you attach the debugger, out of curiosity?

**Comment by codewarrior0** [comment]
In my launcher's JVM options, I wrote:

```
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n
```
