### ISSUE TITLE
Plasma Turbine require Energy Flow circuits while before they required quantum mainframes

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#637]
Submitter: `Wired_4fun#0248`
Body: `OwO issue "Plasma Turbine require Energy Flow circuits while before they required quantum mainframes"`
Attachments:

**Comment by Vyraal1** [comment]
Not a bug, they are both circuitMaster / circuitLudicrous, it's just that the mainframes were removed, so you'll have to tier up even more to get access to plasma turbines now.
