### ISSUE TITLE
Explore into adding RandomPatches to mitigate timeouts/disconnects due to size of pack

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#64]
https://minecraft.curseforge.com/projects/randompatches

Submitter:Vyraal1#0001
Body: OwO issue "Explore into adding RandomPatches to mitigate timeouts/disconnects due to size of pack" "https://minecraft.curseforge.com/projects/randompatches"
Attachments:

**Comment by Saereth** [comment]
added for next update
