### ISSUE TITLE
LuV+ tier Robotarms require wetware processors

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#641]
These robot arms are used to build the assembler to make the wetware processors, locking progression

Submitter: `Wired_4fun#0248`
Body: `OwO issue "LuV+ tier Robotarms require wetware processors" "These robot arms are used to build the assembler to make the wetware processors, locking progression"`
Attachments:

**Comment by Vyraal1** [comment]
circuitLudicrous still includes the Energy Flow Circuit, that's their only option until they can make wetware processors.
