### ISSUE TITLE
Two different Neutron reflectors in oredict

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#642]
There are two different neutron reflectors, and the one that is crafted since change is unable to be crafted into Fusion Coil

Submitter: `Wired_4fun#0248`
Body: `OwO issue "Two different Neutron reflectors in oredict" "There are two different neutron reflectors, and the one that is crafted since change is unable to be crafted into Fusion Coil"`
Attachments:

**Comment by Saereth** [comment]
https://github.com/Shadows-of-Fire/Shadows-of-Greg/issues/8
