### ISSUE TITLE
Move rice oredict from cropVeggie instead of cropGrain, or look to add barley, rye, etc. to the water strainers to help with early grain bait needs

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#648]
Submitter: `Vyraal1#0001`
Body: `OwO issue "Move rice oredict from cropVeggie instead of cropGrain, or look to add barley, rye, etc. to the water strainers to help with early grain bait needs"`
Attachments:

**Comment by Saereth** [comment]
added a separate recipe that uses cropRice to main grain bait, also added tooltips to the baits to tell which ones will and which wont provide beef specifically.
