### ISSUE TITLE
Coke oven hatch uncraftable due to no recipe for gtce bronze tank

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#649]
Submitter: `108r5meme#8686`
Body: `OwO issue "Coke oven hatch uncraftable due to no recipe for gtce bronze tank"`
Attachments:

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/54468275-4d8d0c80-4761-11e9-8225-efe2513dacbe.png)

You dont have this recipe? what version of gregtech does your pack have in it currently?
