### ISSUE TITLE
GTCE Coke oven hatches are nonfunctional

### ISSUE THREAD

**Issue by Saereth** [Vyraal1/FTB-Interactions#650]
no pipes attach and TOP doesnt report any inventory or tanks
![image](https://user-images.githubusercontent.com/9200909/54468332-d73cda00-4761-11e9-92b3-911f1b17f7ce.png)

**Comment by Saereth** [comment]
https://github.com/GregTechCE/GregTech/issues/646

**Comment by Archengius** [comment]
because structure is malformed
