### ISSUE TITLE
When attempting to make glowstone doped silicon boules, silicon ingots are made instead. This is due to the fact that silicon has a second recipe for ingots now, using a circuit with config 1. Additionally, when this happens the circuit is consumed.  This happens when trying to make a normal silicon boule as well.

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#657]
Submitter: `Kel#1990`
Body: `OwO issue "When attempting to make glowstone doped silicon boules, silicon ingots are made instead. This is due to the fact that silicon has a second recipe for ingots now, using a circuit with config 1. Additionally, when this happens the circuit is consumed.  This happens when trying to make a normal silicon boule as well."`
Attachments:

**Comment by Vyraal1** [comment]
https://github.com/GregTechCE/GregTech/issues/648

SoG - Adds a redundant Silicon Dust + Circuit(1) -> Silicon Ingot recipe

GTCE -
Adds faulty Silicon Dust + Circuit(0) -> Silicon Ingot recipe where the circuit is consumed.
Adds faulty Boule recicpes as well where all the Circuit(1) inputs are consumed.
