### ISSUE TITLE
jeiCategory Issues

### ISSUE THREAD

**Issue by Vyraal1** [Vyraal1/FTB-Interactions#679]
https://github.com/CraftTweaker/CraftTweaker/issues/755

**Comment by Vyraal1** [comment]
Reporting to JEI: https://github.com/mezz/JustEnoughItems/issues/1520

**Comment by Saereth** [comment]
relevant:

https://github.com/CoFH/Feedback/issues/1469

https://github.com/mezz/JustEnoughItems/issues/1521

**Comment by Saereth** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues
