### ISSUE TITLE
Still crashing with astral in single player world and corrupting my builds

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#69]
https://gist.github.com/Vyraal1/e95a2e0ac0d63ad1be5a59490fc54b73

Submitter:Vyraal1#0001
Body: OwO issue "Still crashing with astral in single player world and corrupting my builds" "https://gist.github.com/Vyraal1/e95a2e0ac0d63ad1be5a59490fc54b73"
Attachments:

**Comment by Saereth** [comment]
delete your structure matching data file and see if that resolves
