### ISSUE TITLE
discord 'privacy' disclaimer

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#692]
inb4peoplestillcomplain

Submitter: `Teamy#9201`
Body: `OwO issue "discord 'privacy' disclaimer" "inb4peoplestillcomplain"`
Attachments:

**Comment by Saereth** [comment]
on the pack download writeup we need to make sure people the discord mod is included and offers rich presence while playing the game such as showing when you are looking up recipes or using machines etc and can be removed with no impact on the pack if they wish to not include that feature.

**Comment by TeamDman** [comment]
"This pack ships with a Discord Rich Presence mod that provides information about your in-game actions. For some, this might be seen as a privacy issue, so know that it is clientside-only and completely safe to remove from the pack, either by using the launcher or deleting the Discord1.0.#.jar file from the /mods directory."

**Comment by KAfable** [comment]
added on https://www.feed-the-beast.com/projects/ftb-interactions
Right now only Saereth can view it I think
