### ISSUE TITLE
Xaero's Minimap Crash

### ISSUE THREAD

**Issue by NillerMedDild** [Vyraal1/FTB-Interactions#7]
Just posting to link issues, I reported it to the mod dev here:
https://minecraft.curseforge.com/projects/xaeros-minimap/issues/4

**Comment by Vyraal1** [comment]
Hmm, this crash keeps cropping up. I wonder if it has to deal with how the waypoints are stored and whenever we distribute configs to other people.

**Comment by Saereth** [comment]
wouldnt doubt it, wtf does he store that stuff in /config anyway -_-

**Comment by Saereth** [comment]
we havent had any more complaints of this when we stopped distributing the Xaeros configs so might not be an issue as long as we make sure not to do that

**Comment by NillerMedDild** [comment]
It only happened once, I haven't seen it in .44 or .45. Thanks!

**Comment by Discomanco** [comment]
I saw it once in .45, earlier this morning. At least I think it's the same, will double check later
