### ISSUE TITLE
Calculator crashes when putting in big numbers

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#707]
I recommend not putting 11.11T into the crafting calculator, It crashes you https://i.imgur.com/7RrlDjK.png 

Submitter: `Teamy#9201`
Body: `OwO issue "Calculator crashes when putting in big numbers" "I recommend not putting 11.11T into the crafting calculator, It crashes you https://i.imgur.com/7RrlDjK.png "`
Attachments:

**Comment by Saereth** [comment]
still not convinced this mod should be a defaul clientside shipped mod

**Comment by Saereth** [comment]
@Vyraal1

**Comment by KAfable** [comment]
reported this to Towdium, but also closing this since its not being default shipped with the pack
