### ISSUE TITLE
Vis resonator recipe miss match again

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#709]
Flawed quartzite + silver plates -> can't craft it

Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "Vis resonator recipe miss match again" "Flawed quartzite + silver plates -> can't craft it"`
Attachments:

**Comment by IRSmoh** [comment]
this is wrong, and I'm retarded (fixed with redownloading pack)
