### ISSUE TITLE
Add red tooltip to Catalyzing gland saying they don't drop

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#719]
reliquary drops don't drop

Submitter: `FTB Interactions#2470`
Body: `**[TeamDman_9201]** OwO issue "Add red tooltip to Catalyzing gland saying they don't drop" "reliquary drops don't drop"`
Attachments:

**Comment by Vyraal1** [comment]
overrided the original tooltips with lang file instead of using a script
