### ISSUE TITLE
ZenSummoning summons at topmost block

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#72]
Built a altar; 2 Blocks air above then a cobblestone slab (for burning protection) - Zombie spaned ontop of the slab as opposed to ontop of the altar

Submitter: TechnicianLP#5526
Body: OwO issue "ZenSummoning summons at topmost block" "Built a altar; 2 Blocks air above then a cobblestone slab (for burning protection) - Zombie spaned ontop of the slab as opposed to ontop of the altar"
Attachments:

**Comment by Saereth** [comment]
moved to https://github.com/Vyraal1/FTB-Interactions/issues/125

**Comment by TeamDman** [comment]
Mob spawn height is determined by the crafttweaker script, the spawning positioning might need to be revisited later but for now this is working as intended, just build a taller cage
