### ISSUE TITLE
Dimension portal portal blocks aren't indestructible

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#720]
should prob be like a nether portal

Submitter: `FTB Interactions#2470`
Body: `**[TeamDman_9201]** OwO issue "Dimension portal portal blocks aren't indestructible" "should prob be like a nether portal"`
Attachments:

**Comment by Saereth** [comment]
this is like this by design from the mod I dont wanna mess with it with ct and screw something up inadvertently
