### ISSUE TITLE
remove sponge from valid lumberaxe head

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#724]
Submitter: `FTB Interactions#2470`
Body: `**[Saereth]** OwO issue "remove sponge from valid lumberaxe head"`
Attachments:

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/54886214-fe7b6180-4e5b-11e9-9912-bc53c5ca7c67.png)
