### ISSUE TITLE
early game quest "The early game building aid" is unclear which liquid dirt is required

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#725]
game quest The early game building aid is unclear which liquid dirt is required

Submitter: `FTB Interactions#2470`
Body: `**[Mofman]** OwO issue early game quest "The early game building aid" is unclear which liquid dirt is required`
Attachments:

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/54886532-3cc65000-4e5f-11e9-9560-f8bbe9749b6f.png)
