### ISSUE TITLE
Tinkers hatchet can shear leaves without losing durab, sponge hatchet drops leaves, infinite EMC in a forest in a couple of minutes

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#734]
Submitter: `FTB Interactions#2470`
Body: `**[CarbonHUN]** OwO issue "Tinkers hatchet can shear leaves without losing durab, sponge hatchet drops leaves, infinite EMC in a forest in a couple of minutes"`
Attachments:

**Comment by Vyraal1** [comment]
Don't think it's that busted, all items with EMC were designed to be of limited value or renewable in other ways. Rather I think i support this as a neat interaction, depends what @Saereth thinks, I'm fine with either keeping it or killing.

**Comment by Saereth** [comment]
yeah im fine with this
