### ISSUE TITLE
register pams woven cotton (for salt) as a tool so it can be stored in a toolbox for artistan worktables

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#736]
Submitter: `FTB Interactions#2470`
Body: `**[Rdjrjqouqcu]** OwO issue "register pams woven cotton (for salt) as a tool so it can be stored in a toolbox for artistan worktables"`
Attachments:

**Comment by Vyraal1** [comment]
going to decline this suggestion as there needs to be an ingredient in the 3x3 crafting grid otherwise artisan worktables will error, as it stands it's only one item.
