### ISSUE TITLE
Investigate hippogriff saddle issue

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#742]
Fireandice wiki mentions hippogriffs with saddles not working properl

Submitter: `FTB Interactions#2470`
Body: `**[TeamDman_9201]** OwO issue "Investigate hippogriff saddle issue" "Fireandice wiki mentions hippogriffs with saddles not working properl"`
Attachments:

**Comment by Saereth** [comment]
duplicate
