### ISSUE TITLE
"Mana Bucket" quest in Magic tab has different requirements than "Mana Leak" in Overworld tab

### ISSUE THREAD

**Issue by Jomeaga** [Vyraal1/FTB-Interactions#745]
Got a clay bucket of mana, it completes the overworld quest "Mana Leak" however it doesn't complete the "Mana Bucket" quest as it requires a regular bucket of mana.

**Comment by KAfable** [comment]
Sorry about this Jomeaga, but for our sanity, do you mind re-making this in the official tracker? We only used this one during the beta.
