### ISSUE TITLE
alternative to making coal in squeezer from ore

### ISSUE THREAD

**Issue by comical-uk** [Vyraal1/FTB-Interactions#747]
Hi

Would it be possible to add another early method to make coal from ore early game that doesn't rely on the squeezer

I have found that on larger multiplayer servers, as the TPS/latency is bad then the squeezer is not that easy to use, with most jumps not actually registering when performance is worse than ideal

cheers

**Comment by KAfable** [comment]
If possible, try to update the server to v1.1.2. There was a [mod by Shadow](https://minecraft.curseforge.com/projects/id-squeezer-tweak)s that helps address this issue if the tps is poor. 

My question is what do you need coal for so early that other routes cannot provide? Can look into enhancing that as well.

**Comment by comical-uk** [comment]
thanks, I'll pass that on

I was trying to use to to make coal for the sooty marble (but there is an arcane ashes recipe for that too) but I dont think there is any other way of making the coal dust for resistors without requiring coal
