### ISSUE TITLE
GT Machines are using high cpu on servers when they have circuit/mold/partial ingredients

### ISSUE THREAD

**Issue by Highbeam** [Vyraal1/FTB-Interactions#752]
GT Machines with circuits/molds left inside eat a lot of server resources when they are idle.

We have tracked this down so far to Alloy Smelter (with molds in) and Assembling Machine (with circuits).

The Assembling machines (any tier) were eating as much as 4.5%+ and the Alloy Smelter 1.5%+ in the screenshot below (1st and 2nd):

![image](https://user-images.githubusercontent.com/32101225/56354264-8fcbc280-61d3-11e9-9b9f-b1451835d64e.png)

After removing the circuit/mold, things returned to normal...

![image](https://user-images.githubusercontent.com/32101225/56354755-df5ebe00-61d4-11e9-9a01-59fa1c372e9e.png)

The third machine down in the 2nd screenshot (0.5%) is a Mixer that has partial recipe in, waiting for more ingredients.

This can slowly get out of hand if multiple players have many machines with circuits/recipes waiting in them.

**Comment by KAfable** [comment]
This was partially addressed in this PR, but has been a recurrent issue in GTCE for a while now. Judging from mod dev's response, I'm not sure what workarounds/improvements can be made.

https://github.com/GregTechCE/GregTech/issues/468

**Comment by KAfable** [comment]
Actually, do you mind reposting this in the official tracker? this one is now deprecated.
