### ISSUE TITLE
Pulverise Iron Bars = too much iron

### ISSUE THREAD

**Issue by Highbeam** [Vyraal1/FTB-Interactions#753]
It can cost as low as 3 iron ingots to make 8 Iron Bars (in crafting table/assembler = 6 iron rods)

Macerate 1 iron bar = 24 tiny piles (2.65 ingots)

Suggestion:

Change 1 iron bar = 3 tiny piles (8 * 3 = 24 tiny piles so you don't get profit)

**Comment by KAfable** [comment]
Please move to new tracker
