### ISSUE TITLE
Steam Boiler blowing up when adding fuel

### ISSUE THREAD

**Issue by ShaneCourtrille** [Vyraal1/FTB-Interactions#758]
So I know that Boilers can blow up if hot/dry and you add water but I have twice had small steam boilers explode which were full of water but had ran out of fuel.  I add fuel and they've exploded.  

Any ideas on this?

**Comment by KAfable** [comment]
~~Please follow the template with a new issue. Can't reproduce in latest.~~
Actually we moved trackers, please move onto the new tracker on the FTB Team, used the link in the modpack.
