### ISSUE TITLE
Particle Effect related Memory Leak

### ISSUE THREAD

**Issue by Torrenal** [Vyraal1/FTB-Interactions#759]
Not sure what triggered it, ParticleRain has 5 million instances in memory consuming 878MB of ram, ParticleSuspend has 1.2 million instances for another 202MB, ParticleSmokeLarge, ParticleFlame, ParticleSmokeNormal, ParticlePortal all also fit in there . . .  I've even got 'ParticleSerpentBubble' for 11MB, despite not having been in the overworld for a while...

What I have is a heap dump with some additional details (Telemetries, some CPU metrics, some lock state, etc...)

![image](https://user-images.githubusercontent.com/23144113/57989810-809f9500-7a5d-11e9-94f8-8d6cb7055b1d.png)
![image](https://user-images.githubusercontent.com/23144113/57989924-c01ab100-7a5e-11e9-8e04-0a989a3ffab5.png)
![image](https://user-images.githubusercontent.com/23144113/57989964-0839d380-7a5f-11e9-938e-c2be5106a458.png)
[UsingAllTheRams.log](https://github.com/Vyraal1/FTB-Interactions/files/3195795/UsingAllTheRams.log)

Willing to work with you to fix this, but I'm not sure what triggered the leak.
If I had to guess - - whatever manages the particle effects may have died, or otherwise stopped work that includes clearing the list of particles, and in dying/failing, it doesn't replace the queue with a dummy queue that discards particle requests as they arrive - That would allow particle effects to break, without running Minecraft out of memory in the process (and yes, I am that paranoid in my own programming).

**Comment by KAfable** [comment]
Just a heads up this tracker is no longer in use.
