### ISSUE TITLE
Cannot create worlds

### ISSUE THREAD

**Issue by BlackHoleTON618** [Vyraal1/FTB-Interactions#760]
when i click create world button i just falll down to void

**Comment by KAfable** [comment]
Follow the template.

**Comment by KAfable** [comment]
Actually we moved trackers, this one is no longer in use.

**Comment by BlackHoleTON618** [comment]
what do you mean by follow the template i dont do anything i just pressed create world i didint change anything

**Comment by KAfable** [comment]
We moved to a new tracker: https://github.com/FTBTeam/FTB-Interactions/issues
Please use that one, you can also access it from the modpack front page when the pack is loaded.
