### ISSUE TITLE
Blaze causing server crash?

### ISSUE THREAD

**Issue by unkelrara** [Vyraal1/FTB-Interactions#762]
I just got the blaze charm reward, and using it while attacking a blaze has crashed the server 4 times in a row.

**Comment by TeamDman** [comment]
Logs from the server?

**Comment by unkelrara** [comment]
Asking the server host to get them for you.

**Comment by Sanavixx** [comment]
[2019-05-24-3.log.gz](https://github.com/Vyraal1/FTB-Interactions/files/3219998/2019-05-24-3.log.gz)
[crash-2019-05-24_23.08.07-server.txt](https://github.com/Vyraal1/FTB-Interactions/files/3220002/crash-2019-05-24_23.08.07-server.txt)

**Comment by TeamDman** [comment]
Looks like the blaze is crashing when trying to identify whether or not the player is on the same 'team' as the blazes, doesn't seem to be 'our' fault.
Not sure what mod the blaze charm is from, but this needs to go to their tracker as well


pics of relevant info
![image](https://user-images.githubusercontent.com/9356891/58388998-0ab6a300-7ff4-11e9-9d3a-86ff5feb329f.png)

![image](https://user-images.githubusercontent.com/9356891/58388982-dcd15e80-7ff3-11e9-801b-2fcdb212b723.png)


![image](https://user-images.githubusercontent.com/9356891/58388987-e2c73f80-7ff3-11e9-8d7f-45021ff34742.png)

![image](https://user-images.githubusercontent.com/9356891/58389002-12764780-7ff4-11e9-9431-da95f50bef44.png)
