### ISSUE TITLE
Can't craft coagulated plant balls

### ISSUE THREAD

**Issue by FunnyBunny14** [Vyraal1/FTB-Interactions#767]
Even though I'm using a mallet as tool and 4 saplings in a square in the artisan crafting table, I can't craft the coagulated plant balls.
![Screenshot crafting](https://user-images.githubusercontent.com/13102670/61479300-d75d1880-a993-11e9-942d-0b0efdb4cf59.jpg)

**Comment by TeamDman** [comment]
I believe they need water in the table

**Comment by FunnyBunny14** [comment]
You're right :)
