### ISSUE TITLE
New update broke quest tracking

### ISSUE THREAD

**Issue by marcoabit** [Vyraal1/FTB-Interactions#774]
Updated the pack to the new version available on the FTB app. This removed all quests from the questbook icon on the FTB mod.

I also noticed some tool recipes in the worktable were not working.

Downgrading fixed the issues, but I lost progress on my quests

**Comment by Saereth** [comment]
this is the wrong github, you want https://github.com/FTBTeam/FTB-Interactions/issues

your update failed to complete properly is what happened, restore your world from the /backups folder and reupdating, should fix it. They're working on the ftb app still so its far from bug free unfortunately
