### ISSUE TITLE
Infinity Dust doesn't work

### ISSUE THREAD

**Issue by reesercollins** [Vyraal1/FTB-Interactions#776]
I've tried everything: restarting my game, giving myself tons of xp, giving myself tons of flint. Nothing is happening when I left-click on the bedrock with the flint.

**Comment by Saereth** [comment]
earn some xp the normal way, cook stuff in a smelter or whatever, it will update then and start working. Giving xp and getting xp from the questbook doesnt properly register sometimes. If that still doesnt work, sounds like your scripts are messed up and you should reinstall
