### ISSUE TITLE
grass shrub in emc list

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#79]
intentional?

Submitter: Teamy#9201
Body: OwO issue "grass shrub in emc list" "intentional?"
Attachments:

**Comment by Saereth** [comment]
undecided, its in for now but we want to get testing feedback if it should stay or not. definitely alleviates the early string issues, but it may be making plant balls too readily avaialble... hard to say yet

**Comment by Saereth** [comment]
changing plantball recipe instead, should solve the issue
