### ISSUE TITLE
Food Issues Thread

### ISSUE THREAD

**Issue by PsychoSound** [Vyraal1/FTB-Interactions#8]
https://media.discordapp.net/attachments/527215210768105481/527927419039121438/unknown.png
Pineapples are too good of a food source

**Comment by PsychoSound** [comment]
Raw duck, venison, and turkey can not be cooked on a kiln.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/50520141-a5827400-0a8c-11e9-8fd3-7213d5aa285f.png)
Adding to the thread

**Comment by Saereth** [comment]
add rice bread to kiln

**Comment by Saereth** [comment]
all issues up until this comment are now resolved. leaving open for future issues

**Comment by Saereth** [comment]
we havent had any food issues for a while
