### ISSUE TITLE
Wrought Iron Pick cant harvest Rock Crystal Ore

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#85]
Harvest lvl of the ore is Obsidian

Submitter: Interactions#0220
Body: **[TheonlyTazz]** OwO issue "Wrought Iron Pick cant harvest Rock Crystal Ore" "Harvest lvl of the ore is Obsidian"
Attachments:

**Comment by Saereth** [comment]
fixed
