### ISSUE TITLE
Observations from the 2nd Void World playthrough

### ISSUE THREAD

**Issue by cScotPlay** [Vyraal1/FTB-Interactions#88]
Alrighty, here are some thoughts and observations from a second playthrough of the Void World.  We were able to complete the quest line and make it to the Overworld in right at nine hours of gameplay.  This time we played very conservatively to minimize the total material needs in the Void World.  This meant we only set up the basic requirements to get the quests accomplished and prepare for the Overworld i.e. two Kilns, three Strainers, one Ground Trap, etc.  I limited our use of Ore Excavation and restricted our ability to sprint around the starting island to reduce the amount of Hunger and Saturation that we lost.   Below are some of the things we observed during this playthrough.

- Food, Spice of Life, and Hunger – By playing super conservatively, I only needed to eat nine pieces of food and we entered the Overworld with full saturation, hunger, and plenty of food left over from the rewards (That equated to eating one piece of food for each hour of gameplay).  From the first playthrough you all turned off/down the constant drain of saturation.  As I am proud, we were able to make it this far without food being an issue, I wonder if maybe the adjustment swung too far back to the right.
- I love the idea of having to use Low-Grade Charcoal to light the platform early on.  Love the look and feel it brings to the island.  One addition to the Clay Kiln quest may be to either add the Whittled Fire Sticks to the quest or add some verbiage about them in the quest as a way to light the Charcoal Blocks.
- Traps (Ground and Water) – Not sure if it possible with CraftTweaker but maybe add a note to the item that talks about it needed the specific blocks around it i.e. Vanilla Grass/Dirt for Ground Trap.  I’ve noticed a lot of questions regarding that in the Discord and on the server during peoples’ playthrough.  For the Water Trap, might it be possible to add some red text like the Water Filter “Requires 5x5 water to function.”  Pam’s current wiki and older information talk about this only needed 5 sides of the block touching a Water Source.  Myself and my entire chat had issues figuring this out.  Again, I am very unfamiliar with the entire Pam’s mod.
- Enjoy the new feel of the Low Covalence Dust recipe.  Seems to fit nicely
- I was a bit bummed that the Watering Cans were removed but over time and a properly built farm, according to MC mechanics, yielded plenty of crops in a short amount of time.  The only thing I would have used the Watering Can for was to make both the Vivid Grass and Vanilla Grass blocks to spread quicker.  I wonder if there is a mechanic that can turn off the Watering Cans for crops and maybe just keep it for grasses. (This really doesn’t need to be a thing just me thinking.  I put it here as I see some people will piss and moan about it.)
- Pam’s Candles – Is it possible to get them to interact with Dynamic Lights?
- It may be worth adding some verbiage to the Overworld Portal Quest that talks about how to light the portal with Philosophers Stone.
- Enjoyed the Zen Summoning.  I like the touch that it brings and allows me to specifically place where I wanted to mob to spawn.
- Rustic Honey – Is it possible to OreDict Rustic Honey to work with Pam’s Recipes?
- Plant Twine – You have to make Plant Fiber in the Basic Worktable but it’s a vanilla crafting recipe to make Plant Twine.  This requires you to move between two different crafting blocks to make it.  Since we are using the Basic Worktable to make the Twine would there be any negatives to using it to craft Twine?

These were a couple of things that I observed along the way.  So far, I’ve really enjoyed the Void World playthrough and like the feel and flow of it.  Just my opinion, but a few more minor tweaks to assist the newer players in understanding some of the mechanics, as this pack strays from the normal progression many are accustomed to.  --- Overworld here I COME…

**Comment by Saereth** [comment]
ok great post, I've already implemented a bunch of your suggestions, looking forward to your next udpate
